using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Threading;
using System.Windows.Automation;

namespace LittleTomato {
 public class NoteWindow : Window {
  readonly Program app;public readonly Note Note;public readonly RichTextBox Editor;
  ComboBox headingChoice,taskChoice;bool syncingHeading;TextBox title;TextBlock status;Border tint;Button pin;DispatcherTimer saveTimer;
  bool loading,dirty;string lastBody;readonly Stack<EditState> undo=new Stack<EditState>(),redo=new Stack<EditState>();
  class EditState {public string Body;public int Offset;}
  public NoteWindow(Program owner,Note note,NoteDocument doc){
   app=owner;Note=note;Title="便签 · "+note.DisplayTitle;Style=(Style)Application.Current.FindResource(typeof(Window));UI.Chrome(this);Icon=app.IconSource;
   Width=Math.Min(note.Width,SystemParameters.WorkArea.Width-24);Height=Math.Min(note.Height,SystemParameters.WorkArea.Height-24);MinWidth=400;MinHeight=380;WindowStartupLocation=WindowStartupLocation.CenterScreen;Topmost=note.Pinned;
   var root=new Grid();root.RowDefinitions.Add(new RowDefinition{Height=new GridLength(44)});root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});root.RowDefinitions.Add(new RowDefinition());root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
   var chrome=UI.Titlebar(this,"便签 · 随手记，不打断专注",true);foreach(var b in chrome.Children.OfType<Button>()){if(AutomationProperties.GetName(b)=="最小化")b.ToolTip="最小化便签";if(AutomationProperties.GetName(b)=="收起窗口")b.ToolTip="关闭便签，自动保存内容";}root.Children.Add(chrome);
   tint=new Border{Height=3,VerticalAlignment=VerticalAlignment.Top};Grid.SetRow(tint,1);root.Children.Add(tint);
   title=UI.Input("便签标题",note.Title);title.FontSize=18;title.Height=46;title.FontWeight=FontWeights.SemiBold;title.BorderThickness=new Thickness(0);title.Background=Brushes.Transparent;title.ToolTip="标题可留空，自动使用正文第一行";title.Margin=new Thickness(14,8,14,2);var titleHost=new Grid();titleHost.Children.Add(title);var placeholder=UI.Text("标题可留空，直接在下方记录…",14,"Muted");placeholder.Margin=new Thickness(28,8,28,2);placeholder.VerticalAlignment=VerticalAlignment.Center;placeholder.IsHitTestVisible=false;placeholder.Visibility=String.IsNullOrEmpty(title.Text)?Visibility.Visible:Visibility.Collapsed;titleHost.Children.Add(placeholder);title.TextChanged+=(s,e)=>placeholder.Visibility=String.IsNullOrEmpty(title.Text)?Visibility.Visible:Visibility.Collapsed;Grid.SetRow(titleHost,1);root.Children.Add(titleHost);
   var tools=new WrapPanel{Margin=new Thickness(20,4,20,10)};Grid.SetRow(tools,2);root.Children.Add(tools);
   Tool(tools,"B","加粗 · Ctrl+B",()=>Command(EditingCommands.ToggleBold)).FontWeight=FontWeights.Bold;
   Tool(tools,"I","斜体 · Ctrl+I",()=>Command(EditingCommands.ToggleItalic)).FontStyle=FontStyles.Italic;
   Tool(tools,"U","下划线 · Ctrl+U",()=>Command(EditingCommands.ToggleUnderline));
   var strike=Tool(tools,"S","删除线",()=>Decoration(TextDecorationLocation.Strikethrough));strike.Content=new TextBlock{Text="S",TextDecorations=TextDecorations.Strikethrough};
   Tool(tools,"荧光","文字高亮",Highlight);
   var heading=new ComboBox{Style=(Style)Application.Current.FindResource("NoteCombo"),Width=84,Margin=new Thickness(0,3,6,3),Focusable=false,ToolTip="段落样式"};heading.Items.Add("正文");heading.Items.Add("大标题");heading.Items.Add("小标题");heading.SelectedIndex=0;heading.SelectionChanged+=(s,e)=>{if(Editor!=null&&!syncingHeading)SetKind(new[]{"body","h1","h2"}[heading.SelectedIndex]);};headingChoice=heading;tools.Children.Add(heading);AutomationProperties.SetName(heading,"段落样式");
   Tool(tools,"• 列表","分点列表",()=>SetKind("bullet"));Tool(tools,"1. 列表","编号列表",()=>SetKind("number"));Tool(tools,"待办","待办勾选",()=>SetKind("check"));
   Tool(tools,"缩进","增加缩进 · Tab",()=>Indent(1));Tool(tools,"反缩进","减少缩进 · Shift+Tab",()=>Indent(-1));
   var more=Tool(tools,"更多","更多编辑操作",()=>{});var menu=new ContextMenu();Menu(menu,"插入链接",InsertLink);Menu(menu,"撤销 · Ctrl+Z",UndoEdit);Menu(menu,"重做 · Ctrl+Y",RedoEdit);Menu(menu,"清除文字格式",ClearFormat);menu.Items.Add(new Separator());Menu(menu,"移到回收站",()=>app.Notes.Delete(Note));more.Click+=(s,e)=>{menu.PlacementTarget=more;menu.IsOpen=true;};
   Editor=new RichTextBox{BorderThickness=new Thickness(0),Padding=new Thickness(24,12,24,18),VerticalScrollBarVisibility=ScrollBarVisibility.Auto,AcceptsTab=false,IsDocumentEnabled=true,IsUndoEnabled=false,FontSize=15,Background=Brushes.Transparent};Editor.SetResourceReference(Control.ForegroundProperty,"Ink");Editor.SetResourceReference(RichTextBox.CaretBrushProperty,"Ink");AutomationProperties.SetName(Editor,"便签正文");Grid.SetRow(Editor,3);root.Children.Add(Editor);
   var context=new ContextMenu();foreach(var name in new[]{"剪切","复制","粘贴"}){string action=name;Menu(context,action,()=>{Editor.Focus();if(action=="剪切")Editor.Cut();else if(action=="复制")Editor.Copy();else Editor.Paste();});}context.Items.Add(new Separator());Menu(context,"撤销",UndoEdit);Menu(context,"重做",RedoEdit);Editor.ContextMenu=context;
   DataObject.AddPastingHandler(Editor,(s,e)=>{if(e.SourceDataObject.GetDataPresent(DataFormats.UnicodeText))e.FormatToApply=DataFormats.UnicodeText;else e.CancelCommand();});
   var footer=new WrapPanel{Margin=new Thickness(20,8,20,4)};Grid.SetRow(footer,4);root.Children.Add(footer);
   pin=Tool(footer,note.Pinned?"已置顶":"置顶","保持便签在其他窗口上方",()=>{Note.Pinned=!Note.Pinned;Topmost=Note.Pinned;pin.Content=Note.Pinned?"已置顶":"置顶";Schedule();});
   var colors=new ComboBox{Style=(Style)Application.Current.FindResource("NoteCombo"),Width=86,Margin=new Thickness(0,3,8,3)};foreach(var c in new[]{"奶油","鼠尾草","浅玫瑰"})colors.Items.Add(c);colors.SelectedIndex=Array.IndexOf(new[]{"paper","sage","rose"},note.Color);colors.SelectionChanged+=(s,e)=>{Note.Color=new[]{"paper","sage","rose"}[Math.Max(0,colors.SelectedIndex)];ApplyColor();Schedule();};footer.Children.Add(colors);AutomationProperties.SetName(colors,"便签颜色");
   Tool(footer,"转为任务","创建任务，保留原便签",()=>{if(Flush()){app.Notes.ToTask(Note);RefreshTaskChoice();}});
   var task=new ComboBox{Style=(Style)Application.Current.FindResource("NoteCombo"),Width=160,Margin=new Thickness(0,3,0,3),ToolTip="可选：关联已有任务"};task.Items.Add(new ComboBoxItem{Content="独立便签",Tag=(string)null});foreach(var t in app.Data.Tasks.Where(t=>!t.Archived))task.Items.Add(new ComboBoxItem{Content=t.Title,Tag=t.Id});task.SelectedItem=task.Items.Cast<ComboBoxItem>().FirstOrDefault(i=>(string)i.Tag==note.TaskId)??task.Items[0];task.SelectionChanged+=(s,e)=>{if(task.SelectedItem==null)return;Note.TaskId=(string)((ComboBoxItem)task.SelectedItem).Tag;Schedule();};footer.Children.Add(task);taskChoice=task;AutomationProperties.SetName(task,"关联任务");
   status=UI.Text("已保存 · Ctrl+单击打开链接",11,"Muted");status.Margin=new Thickness(24,2,24,14);Grid.SetRow(status,5);root.Children.Add(status);Content=root;
   saveTimer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(650)};saveTimer.Tick+=(s,e)=>Flush();
   Render(doc);lastBody=Store.Encode(Capture());ApplyColor();
   title.TextChanged+=(s,e)=>{Note.Title=title.Text;Schedule();};Editor.TextChanged+=(s,e)=>Record();Editor.SelectionChanged+=(s,e)=>SyncHeading();SyncHeading();Editor.PreviewKeyDown+=Keys;
   Editor.PreviewTextInput+=(s,e)=>{if(e.Text==" "){var p=Editor.CaretPosition.Paragraph;if(p==null)return;string prefix=new TextRange(p.ContentStart,Editor.CaretPosition).Text;string kind=prefix=="-"||prefix=="*"?"bullet":prefix=="1."?"number":prefix=="[]"||prefix=="[ ]"?"check":null;if(kind!=null&&Plain(p)==prefix){loading=true;new TextRange(p.ContentStart,Editor.CaretPosition).Text="";loading=false;SetKind(kind);e.Handled=true;}else Dispatcher.BeginInvoke(new Action(AutoLink),DispatcherPriority.Background);}};
   Editor.PreviewMouseLeftButtonDown+=(s,e)=>{if(Keyboard.Modifiers!=ModifierKeys.Control)return;var pos=Editor.GetPositionFromPoint(e.GetPosition(Editor),true);var p=pos==null?null:pos.Paragraph;if(p==null)return;for(DependencyObject parent=pos.Parent;parent!=null;parent=LogicalTreeHelper.GetParent(parent)){var target=parent as Hyperlink;if(target!=null&&target.NavigateUri!=null){OpenLink(target.NavigateUri.AbsoluteUri);e.Handled=true;return;}}string text=Plain(p);int index=new TextRange(p.ContentStart,pos).Text.Length;foreach(Match match in Regex.Matches(text,@"https?://[^\s<>]+")){if(index>=match.Index&&index<=match.Index+match.Length){OpenLink(match.Value.TrimEnd('.',',','。','，',')','）'));e.Handled=true;break;}}};
   CommandBindings.Add(new CommandBinding(ApplicationCommands.Undo,(s,e)=>UndoEdit(),(s,e)=>{e.CanExecute=true;e.Handled=true;}));CommandBindings.Add(new CommandBinding(ApplicationCommands.Redo,(s,e)=>RedoEdit(),(s,e)=>{e.CanExecute=true;e.Handled=true;}));
   Closing+=(s,e)=>{if(!Flush())e.Cancel=true;};Closed+=(s,e)=>saveTimer.Stop();Loaded+=(s,e)=>{Editor.Focus();};SizeChanged+=(s,e)=>{if(IsLoaded&&WindowState==WindowState.Normal){Note.Width=ActualWidth;Note.Height=ActualHeight;Schedule();}};
  }
  Button Tool(Panel panel,string text,string help,Action action){var b=UI.Button(text,action,false);b.Padding=new Thickness(9,6,9,6);b.MinHeight=32;b.MinWidth=30;b.FontSize=12;b.Margin=new Thickness(0,3,5,3);b.Focusable=false;b.ToolTip=help;AutomationProperties.SetName(b,help);panel.Children.Add(b);return b;}
  static void Menu(ContextMenu m,string text,Action action){var item=new MenuItem{Header=text};item.Click+=(s,e)=>action();m.Items.Add(item);}
  void SyncHeading(){if(loading||headingChoice==null)return;var p=Editor.CaretPosition.Paragraph;string kind=p==null?"body":p.Tag as string;syncingHeading=true;headingChoice.SelectedIndex=kind=="h1"?1:kind=="h2"?2:0;syncingHeading=false;}
  void RefreshTaskChoice(){if(taskChoice==null)return;string id=Note.TaskId;taskChoice.Items.Clear();taskChoice.Items.Add(new ComboBoxItem{Content="独立便签",Tag=(string)null});foreach(var t in app.Data.Tasks.Where(t=>!t.Archived))taskChoice.Items.Add(new ComboBoxItem{Content=t.Title,Tag=t.Id});taskChoice.SelectedItem=taskChoice.Items.Cast<ComboBoxItem>().FirstOrDefault(i=>(string)i.Tag==id)??taskChoice.Items[0];}
  void ApplyColor(){if(tint!=null)tint.Background=new SolidColorBrush((Color)ColorConverter.ConvertFromString(Note.Color=="sage"?"#98B29B":Note.Color=="rose"?"#D4A1A3":"#D9BA77"));}
  void Schedule(){if(loading||saveTimer==null)return;dirty=true;Note.Updated=DateTime.UtcNow.Ticks;Title="便签 · "+Note.DisplayTitle;status.Text="正在保存…";saveTimer.Stop();saveTimer.Start();}
  public bool Flush(){if(saveTimer!=null)saveTimer.Stop();if(!dirty)return true;if(!app.Save()){status.Text="尚未保存 · 请重试";return false;}dirty=false;status.Text="已保存 · Ctrl+单击打开链接";app.Notes.Changed();return true;}
  int Offset(){return Editor.Document.ContentStart.GetOffsetToPosition(Editor.CaretPosition);}
  public void Record(){if(loading)return;var doc=Capture();string body=Store.Encode(doc);if(body==lastBody)return;if(lastBody!=null){undo.Push(new EditState{Body=lastBody,Offset=Offset()});if(undo.Count>200){var keep=undo.Take(150).Reverse().ToArray();undo.Clear();foreach(var state in keep)undo.Push(state);}redo.Clear();}lastBody=body;Note.Body=body;Note.PlainText=doc.PlainText;Schedule();}
  public void UndoEdit(){History(undo,redo);}
  public void RedoEdit(){History(redo,undo);}
  void History(Stack<EditState> from,Stack<EditState> to){if(from.Count==0)return;to.Push(new EditState{Body=lastBody,Offset=Offset()});var state=from.Pop();var doc=NoteCodec.Decode(state.Body);Render(doc);lastBody=state.Body;Note.Body=state.Body;Note.PlainText=doc.PlainText;int max=Editor.Document.ContentStart.GetOffsetToPosition(Editor.Document.ContentEnd);Editor.CaretPosition=Editor.Document.ContentStart.GetPositionAtOffset(Math.Min(max,Math.Max(0,state.Offset)))??Editor.Document.ContentEnd;Editor.Focus();Schedule();}
  static string Plain(Paragraph p){return new TextRange(p.ContentStart,p.ContentEnd).Text.Replace("\uFFFC","");}
  static IEnumerable<Paragraph> Paragraphs(BlockCollection blocks){foreach(var b in blocks){var p=b as Paragraph;if(p!=null)yield return p;var list=b as System.Windows.Documents.List;if(list!=null)foreach(var item in list.ListItems)foreach(var child in Paragraphs(item.Blocks))yield return child;}}
  public NoteDocument Capture(){var doc=new NoteDocument();foreach(var p in Paragraphs(Editor.Document.Blocks)){var box=p.Inlines.OfType<InlineUIContainer>().Select(i=>i.Child).OfType<CheckBox>().FirstOrDefault();var list=p.Parent is ListItem?((ListItem)p.Parent).Parent as System.Windows.Documents.List:null;var block=new NoteBlock{Kind=box!=null?"check":list!=null?(list.MarkerStyle==TextMarkerStyle.Decimal?"number":"bullet"):(p.Tag as string??"body"),Done=box!=null&&box.IsChecked==true,Indent=(int)Math.Round((list==null?p.Margin.Left:list.Margin.Left)/22)};ReadInlines(p.Inlines,block.Runs,null);doc.Blocks.Add(block);}return doc;}
  static bool HasDecoration(Inline inline,TextDecorationLocation location){for(TextElement el=inline;el is Inline;el=el.Parent as TextElement){if((el.Tag as string)=="completion")continue;var decorations=el.ReadLocalValue(Inline.TextDecorationsProperty) as TextDecorationCollection;if(decorations!=null&&decorations.Any(d=>d.Location==location))return true;}return false;}
  static void ReadInlines(InlineCollection inlines,List<NoteRun> output,string link){foreach(var i in inlines){var run=i as Run;var hyperlink=i as Hyperlink;var span=i as Span;if(run!=null)output.Add(new NoteRun{Text=run.Text,Bold=run.FontWeight==FontWeights.Bold||run.FontWeight==FontWeights.SemiBold,Italic=run.FontStyle==FontStyles.Italic,Underline=HasDecoration(run,TextDecorationLocation.Underline),Strike=HasDecoration(run,TextDecorationLocation.Strikethrough),Highlight=run.Background is SolidColorBrush&&((SolidColorBrush)run.Background).Color.A!=0,Link=link});else if(i is LineBreak)output.Add(new NoteRun{Text="\n"});else if(span!=null)ReadInlines(span.Inlines,output,hyperlink!=null&&hyperlink.NavigateUri!=null?hyperlink.NavigateUri.AbsoluteUri:link);}}
  public void Render(NoteDocument doc){loading=true;try{var flow=new FlowDocument{FontFamily=new FontFamily("Segoe UI, Microsoft YaHei UI"),FontSize=15,PagePadding=new Thickness(0),LineHeight=25};flow.SetResourceReference(TextElement.ForegroundProperty,"Ink");int number=0;foreach(var block in doc.Blocks){var p=new Paragraph{Tag=block.Kind,Margin=new Thickness(block.Indent*22,0,0,9),FontSize=block.Kind=="h1"?24:block.Kind=="h2"?19:15};if(block.Kind=="h1"||block.Kind=="h2"){p.FontWeight=FontWeights.SemiBold;p.Margin=new Thickness(block.Indent*22,9,0,10);}InlineCollection target=p.Inlines;
    if(block.Kind=="check"){var box=new CheckBox{IsChecked=block.Done,Margin=new Thickness(0,0,7,0),Focusable=false,VerticalAlignment=VerticalAlignment.Center,ToolTip="标记完成"};AutomationProperties.SetName(box,"便签待办勾选");p.Inlines.Add(new InlineUIContainer(box){BaselineAlignment=BaselineAlignment.Center});var completion=new Span{Tag="completion"};if(block.Done){completion.SetResourceReference(TextElement.ForegroundProperty,"Muted");completion.TextDecorations=TextDecorations.Strikethrough;}p.Inlines.Add(completion);target=completion.Inlines;box.Click+=(s,e)=>{loading=true;if(box.IsChecked==true){completion.SetResourceReference(TextElement.ForegroundProperty,"Muted");completion.TextDecorations=TextDecorations.Strikethrough;}else{completion.ClearValue(TextElement.ForegroundProperty);completion.TextDecorations=null;}loading=false;Record();};}
    foreach(var r in block.Runs){var run=new Run(r.Text){FontWeight=r.Bold?FontWeights.Bold:FontWeights.Normal,FontStyle=r.Italic?FontStyles.Italic:FontStyles.Normal};if(block.Kind=="h1"||block.Kind=="h2")run.FontWeight=FontWeights.SemiBold;var decorations=new TextDecorationCollection();if(r.Underline)decorations.Add(TextDecorations.Underline);if(r.Strike)decorations.Add(TextDecorations.Strikethrough);run.TextDecorations=decorations;if(r.Highlight)run.Background=new SolidColorBrush(Color.FromArgb(95,224,173,45));if(NoteCodec.SafeLink(r.Link)){var h=new Hyperlink(run){NavigateUri=new Uri(r.Link),ToolTip="Ctrl+单击打开链接"};h.SetResourceReference(TextElement.ForegroundProperty,"Accent");h.RequestNavigate+=(s,e)=>{if(Keyboard.Modifiers==ModifierKeys.Control)OpenLink(e.Uri.AbsoluteUri);e.Handled=true;};target.Add(h);}else target.Add(run);}
    if(block.Runs.Count==0)target.Add(new Run(""));
    if(block.Kind=="bullet"||block.Kind=="number"){number=block.Kind=="number"?number+1:0;var list=new System.Windows.Documents.List{MarkerStyle=block.Kind=="number"?TextMarkerStyle.Decimal:TextMarkerStyle.Disc,StartIndex=Math.Max(1,number),Margin=new Thickness(block.Indent*22,0,0,0),Padding=new Thickness(24,0,0,0)};p.Margin=new Thickness(0,0,0,9);list.ListItems.Add(new ListItem(p));flow.Blocks.Add(list);}else{number=0;flow.Blocks.Add(p);}}
    if(flow.Blocks.Count==0)flow.Blocks.Add(new Paragraph());Editor.Document=flow;
   }finally{loading=false;}}
  List<int> SelectedBlocks(){var ps=Paragraphs(Editor.Document.Blocks).ToList();var start=Editor.Selection.Start.Paragraph;var end=Editor.Selection.End.Paragraph;int a=Math.Max(0,ps.IndexOf(start)),b=Math.Max(a,ps.IndexOf(end));return Enumerable.Range(a,b-a+1).ToList();}
  public void SetKind(string kind){var indices=SelectedBlocks();var doc=Capture();bool toggle=kind=="bullet"||kind=="number"||kind=="check";string target=toggle&&indices.All(i=>doc.Blocks[i].Kind==kind)?"body":kind;foreach(int i in indices){doc.Blocks[i].Kind=target;if(target!="check")doc.Blocks[i].Done=false;}Render(doc);Editor.CaretPosition=Paragraphs(Editor.Document.Blocks).ElementAt(indices.Last()).ContentEnd;Editor.Focus();Record();}
  public void Indent(int direction){var indices=SelectedBlocks();var doc=Capture();foreach(int i in indices)doc.Blocks[i].Indent=Math.Max(0,Math.Min(6,doc.Blocks[i].Indent+direction));Render(doc);Editor.CaretPosition=Paragraphs(Editor.Document.Blocks).ElementAt(indices.Last()).ContentEnd;Editor.Focus();Record();}
  public void RefreshTheme(){Editor.Document.Foreground=UI.Brush("Ink");foreach(var p in Paragraphs(Editor.Document.Blocks))RefreshInlines(p.Inlines);}
  void RefreshInlines(InlineCollection collection){foreach(var inline in collection){var h=inline as Hyperlink;if(h!=null)h.Foreground=UI.Brush("Accent");var span=inline as Span;if(span!=null){if((span.Tag as string)=="completion"&&span.TextDecorations!=null&&span.TextDecorations.Any())span.Foreground=UI.Brush("Muted");RefreshInlines(span.Inlines);}}}
  public void Command(RoutedUICommand command){Editor.Focus();command.Execute(null,Editor);Record();}
  public void Decoration(TextDecorationLocation location){Editor.Focus();var current=Editor.Selection.GetPropertyValue(Inline.TextDecorationsProperty) as TextDecorationCollection;var value=current==null?new TextDecorationCollection():current.Clone();bool had=value.Any(d=>d.Location==location);foreach(var d in value.Where(d=>d.Location==location).ToList())value.Remove(d);if(!had)value.Add(location==TextDecorationLocation.Strikethrough?TextDecorations.Strikethrough:TextDecorations.Underline);Editor.Selection.ApplyPropertyValue(Inline.TextDecorationsProperty,value);Record();}
  public void Highlight(){Editor.Focus();var brush=Editor.Selection.GetPropertyValue(TextElement.BackgroundProperty) as SolidColorBrush;Editor.Selection.ApplyPropertyValue(TextElement.BackgroundProperty,brush!=null&&brush.Color.A!=0?Brushes.Transparent:new SolidColorBrush(Color.FromArgb(95,224,173,45)));Record();}
  public void ClearFormat(){Editor.Focus();Editor.Selection.ApplyPropertyValue(TextElement.FontWeightProperty,FontWeights.Normal);Editor.Selection.ApplyPropertyValue(TextElement.FontStyleProperty,FontStyles.Normal);Editor.Selection.ApplyPropertyValue(Inline.TextDecorationsProperty,new TextDecorationCollection());Editor.Selection.ApplyPropertyValue(TextElement.BackgroundProperty,Brushes.Transparent);Record();}
  void Keys(object sender,KeyEventArgs e){if(Keyboard.Modifiers==ModifierKeys.Control&&(e.Key==Key.Z||e.Key==Key.Y)){if(e.Key==Key.Z)UndoEdit();else RedoEdit();e.Handled=true;return;}if(e.Key==Key.Tab){Indent((Keyboard.Modifiers&ModifierKeys.Shift)!=0?-1:1);e.Handled=true;return;}if(e.Key!=Key.Enter||Keyboard.Modifiers!=ModifierKeys.None)return;var p=Editor.CaretPosition.Paragraph;if(p==null)return;var ps=Paragraphs(Editor.Document.Blocks).ToList();var b=Capture().Blocks[ps.IndexOf(p)];if(b.Kind=="body")return;e.Handled=true;
   if(String.IsNullOrWhiteSpace(Plain(p))){SetKind("body");return;}
   if(b.Kind=="bullet"||b.Kind=="number"){loading=true;EditingCommands.EnterParagraphBreak.Execute(null,Editor);loading=false;Record();return;}
   loading=true;Editor.Selection.Text="";Editor.CaretPosition=Editor.CaretPosition.InsertParagraphBreak();loading=false;var next=Editor.CaretPosition.Paragraph;if(next!=null){next.Tag="body";next.FontSize=15;next.FontWeight=FontWeights.Normal;}if(b.Kind=="check")SetKind("check");else if(b.Kind=="h1"||b.Kind=="h2")SetKind("body");else Record();
  }
  static TextPointer AtCharacter(Paragraph p,int count){var pos=p.ContentStart;while(pos!=null&&pos.CompareTo(p.ContentEnd)<0){if(pos.GetPointerContext(LogicalDirection.Forward)==TextPointerContext.Text){string text=pos.GetTextInRun(LogicalDirection.Forward);if(count<=text.Length)return pos.GetPositionAtOffset(count);count-=text.Length;pos=pos.GetPositionAtOffset(text.Length);}else pos=pos.GetNextContextPosition(LogicalDirection.Forward);}return p.ContentEnd;}
  void AutoLink(){var p=Editor.CaretPosition.Paragraph;if(p==null)return;string before=new TextRange(p.ContentStart,Editor.CaretPosition).Text;var match=Regex.Match(before,@"https?://[^\s<>]+(?=\s$)");if(!match.Success||!NoteCodec.SafeLink(match.Value))return;var start=AtCharacter(p,match.Index);var end=AtCharacter(p,match.Index+match.Length);if(start.Parent is Hyperlink||start.Parent is Run&&((Run)start.Parent).Parent is Hyperlink)return;loading=true;var h=new Hyperlink(start,end){NavigateUri=new Uri(match.Value),ToolTip="Ctrl+单击打开链接"};h.SetResourceReference(TextElement.ForegroundProperty,"Accent");h.RequestNavigate+=(s,e)=>{if(Keyboard.Modifiers==ModifierKeys.Control)OpenLink(e.Uri.AbsoluteUri);e.Handled=true;};loading=false;Record();}
  void InsertLink(){var dialog=UI.Dialog(this,"插入链接",380,205);var field=UI.Input("网址","https://");var panel=UI.Stack(UI.Label("网址 · 支持 https:// 或 http://"),field);panel.Margin=new Thickness(20);panel.Children.Add(UI.Button("插入",()=>{if(!NoteCodec.SafeLink(field.Text)){UI.Notice(dialog,"请输入完整的 http 或 https 网址。");return;}dialog.DialogResult=true;},true));dialog.Content=panel;if(dialog.ShowDialog()!=true)return;Editor.Focus();loading=true;if(Editor.Selection.IsEmpty){var start=Editor.CaretPosition;var run=new Run(field.Text,start);var link=new Hyperlink(run.ElementStart,run.ElementEnd){NavigateUri=new Uri(field.Text)};link.SetResourceReference(TextElement.ForegroundProperty,"Accent");Editor.CaretPosition=link.ElementEnd;}else{var link=new Hyperlink(Editor.Selection.Start,Editor.Selection.End){NavigateUri=new Uri(field.Text)};link.SetResourceReference(TextElement.ForegroundProperty,"Accent");}loading=false;Record();}
  void OpenLink(string link){if(!NoteCodec.SafeLink(link))return;try{System.Diagnostics.Process.Start(link);}catch(Exception ex){UI.Notice(this,"无法打开链接："+ex.Message);}}
 }
}
