using System;
using System.Collections.Generic;
using System.Linq;

namespace LittleTomato {
 public static partial class SelfTests {
  static NoteDocument GroupDocument(){return new NoteDocument{Version=2,Blocks=new List<NoteBlock>{
   new NoteBlock{Kind="number",Checklist=true,Runs=new List<NoteRun>{new NoteRun{Text="整理思路",Bold=true}}},
   new NoteBlock{Kind="number",Checklist=true,Runs=new List<NoteRun>{new NoteRun{Text="小项目"}}},
   new NoteBlock{Kind="number",Checklist=true,Indent=1,Runs=new List<NoteRun>{new NoteRun{Text="完成原型"}}},
   new NoteBlock{Kind="number",Checklist=true,Runs=new List<NoteRun>{new NoteRun{Text="阅读"}}}}};}
  static Note GroupNote(AppData data,NoteDocument doc){var note=new Note{Title="今天的清单",Body=Store.Encode(doc),PlainText=doc.PlainText};data.Notes.Add(note);return note;}
  static void GroupTests(){
   Test("编号清单转换为带缩进分支的任务组",()=>{var d=new AppData();var doc=GroupDocument();var n=GroupNote(d,doc);var g=NoteTasks.Convert(d,n,doc);Assert(d.Tasks.Count==5&&g.Title==n.DisplayTitle&&g.IsGroup,"group and four tasks");var parent=NoteTasks.Linked(d,n,doc.Blocks[1].Id);Assert(NoteTasks.Linked(d,n,doc.Blocks[2].Id).ParentId==parent.Id&&NoteTasks.Linked(d,n,doc.Blocks[3].Id).ParentId==g.Id,"nested and outdented hierarchy");Assert(doc.Blocks[0].Runs[0].Bold&&doc.Blocks[2].Indent==1,"format untouched");Assert(d.Tasks.Where(t=>!t.IsGroup).All(t=>t.Minutes==25&&t.Planned==1),"one default pomodoro per item");});
   Test("重复更新不重复建任务并保留自定义时长和记录",()=>{var d=new AppData();var doc=GroupDocument();var n=GroupNote(d,doc);var g=NoteTasks.Convert(d,n,doc);var first=NoteTasks.Linked(d,n,doc.Blocks[0].Id);first.Minutes=45;first.Planned=3;d.Sessions.Add(new Session{TaskId=first.Id,Seconds=87});doc.Blocks[0].Runs[0].Text="重新整理";NoteTasks.Convert(d,n,doc);Assert(d.Tasks.Count==5&&first.Title=="重新整理"&&first.Minutes==45&&first.Planned==3&&d.Sessions[0].TaskId==first.Id,"stable identity and configuration");Assert(NoteTasks.Group(d,n)==g,"stable group");});
   Test("旧单任务升级保留根任务计时和历史",()=>{FakeClock c;var e=New(out c);var old=e.Selected;e.Start(old);Advance(e,c,12);var doc=GroupDocument();var n=GroupNote(e.Data,doc);n.TaskId=old.Id;var active=e.Data.Active;var g=NoteTasks.Convert(e.Data,n,doc);Assert(g==old&&Object.ReferenceEquals(e.Data.Active,active)&&active.Elapsed==12&&active.Running,"conversion does not switch timer");e.End();Close(NoteTasks.Total(e,g),12,"old root time retained");});
   Test("相同标题条目与不同便签独立关联",()=>{var d=new AppData();var doc=GroupDocument();doc.Blocks[1].Runs[0].Text=doc.Blocks[0].Runs[0].Text;var n=GroupNote(d,doc);NoteTasks.Convert(d,n,doc);var n2=GroupNote(d,NoteCodec.Decode(Store.Encode(doc)));NoteTasks.Convert(d,n2,NoteCodec.Decode(n2.Body));Assert(d.Tasks.Count==10&&NoteTasks.Linked(d,n,doc.Blocks[0].Id)!=NoteTasks.Linked(d,n,doc.Blocks[1].Id)&&NoteTasks.Linked(d,n,doc.Blocks[0].Id)!=NoteTasks.Linked(d,n2,doc.Blocks[0].Id),"IDs not titles determine association");});
   Test("空条目与普通正文不生成任务",()=>{var d=new AppData();var doc=new NoteDocument();doc.Blocks.Add(new NoteBlock{Kind="number"});doc.Blocks.Add(new NoteBlock{Runs=new List<NoteRun>{new NoteRun{Text="说明文字"}}});var n=GroupNote(d,doc);Assert(NoteTasks.Convert(d,n,doc)==null&&d.Tasks.Count==0,"no empty group");});
   Test("删除清单项保留历史且撤销后重新关联",()=>{var d=new AppData();var doc=GroupDocument();var n=GroupNote(d,doc);NoteTasks.Convert(d,n,doc);var removed=doc.Blocks[0];var task=NoteTasks.Linked(d,n,removed.Id);d.Sessions.Add(new Session{TaskId=task.Id,Seconds=60});doc.Blocks.RemoveAt(0);NoteTasks.Convert(d,n,doc);Assert(d.Tasks.Contains(task)&&d.Sessions.Count==1,"no destructive deletion");doc.Blocks.Insert(0,removed);NoteTasks.Convert(d,n,doc);Assert(d.Tasks.Count==5&&NoteTasks.Linked(d,n,removed.Id)==task,"undo reuses original identity");});
   Test("更新缩进与顺序保留任务身份",()=>{var d=new AppData();var doc=GroupDocument();var n=GroupNote(d,doc);var g=NoteTasks.Convert(d,n,doc);var task=NoteTasks.Linked(d,n,doc.Blocks[2].Id);doc.Blocks[2].Indent=0;var moved=doc.Blocks[2];doc.Blocks.RemoveAt(2);doc.Blocks.Insert(0,moved);NoteTasks.Convert(d,n,doc);Assert(task.ParentId==g.Id&&task.NoteOrder==0&&d.Tasks.Count==5,"move and outdent");});
   Test("正文同步不创建新增空任务也不切换计时",()=>{FakeClock c;var e=New(out c);e.Start(e.Selected);var current=e.Data.Active;var doc=GroupDocument();var n=GroupNote(e.Data,doc);NoteTasks.Convert(e.Data,n,doc);int count=e.Data.Tasks.Count;doc.Blocks.Add(new NoteBlock{Kind="number",Runs=new List<NoteRun>{new NoteRun{Text="新增想法"}}});doc.Blocks[0].Runs[0].Text="编辑中的任务";NoteTasks.SyncExisting(e,n,doc);Assert(e.Data.Tasks.Count==count&&Object.ReferenceEquals(current,e.Data.Active)&&current.Running,"passive edits leave timer and task count");NoteTasks.Convert(e.Data,n,doc);Assert(e.Data.Tasks.Count==count+1,"explicit refresh adds item");});
   Test("便签完成当前任务保存专注且支持取消完成",()=>{var c=new FakeClock();var e=new Engine(new AppData(),c);var doc=GroupDocument();var n=GroupNote(e.Data,doc);NoteTasks.Convert(e.Data,n,doc);var task=NoteTasks.Linked(e.Data,n,doc.Blocks[0].Id);e.Start(task);Advance(e,c,8);doc.Blocks[0].Done=true;NoteTasks.SyncExisting(e,n,doc);Assert(task.Done&&e.Data.Active==null,"completed current task ends");Close(e.Total(task.Id),8,"time saved");doc.Blocks[0].Done=false;NoteTasks.SyncExisting(e,n,doc);Assert(!task.Done&&e.Data.Active==null,"undo completion does not auto-start");});
   Test("任务完成反向同步便签且保持编号和原格式",()=>{var d=new AppData();var doc=GroupDocument();var n=GroupNote(d,doc);NoteTasks.Convert(d,n,doc);var e=new Engine(d,new FakeClock());var task=NoteTasks.Linked(d,n,doc.Blocks[0].Id);e.MarkDone(task);var updated=NoteCodec.Decode(n.Body).Blocks[0];Assert(updated.Done&&updated.Kind=="number"&&updated.Checklist&&updated.Runs[0].Bold,"reverse completion preserves format");e.MarkDone(task);Assert(!NoteCodec.Decode(n.Body).Blocks[0].Done,"reverse reopen");});
   Test("任务组汇总不改变全局统计且只启动一项",()=>{var c=new FakeClock();var e=new Engine(new AppData(),c);var doc=GroupDocument();var n=GroupNote(e.Data,doc);var g=NoteTasks.Convert(e.Data,n,doc);var first=NoteTasks.Linked(e.Data,n,doc.Blocks[0].Id);e.Start(g);Assert(e.Current==first,"group starts first pending task");Advance(e,c,9);e.End();first.Done=true;e.Start(g);Assert(e.Current!=first&&!e.Current.IsGroup,"next pending task");Advance(e,c,6);Close(NoteTasks.Total(e,g),15,"aggregate");Close(e.Data.Tasks.Sum(t=>e.Total(t.Id)),15,"global no double counting");});
   Test("完成番茄不会擅自完成待办或开启下一分支",()=>{var c=new FakeClock();var e=new Engine(new AppData(),c);var doc=GroupDocument();var n=GroupNote(e.Data,doc);var g=NoteTasks.Convert(e.Data,n,doc);var task=NoteTasks.Next(e.Data,g);task.Minutes=1;e.Start(task);Advance(e,c,60);Assert(!task.Done&&e.Data.Active.Kind=="short"&&!e.Data.Active.Running&&e.Data.Active.TaskId==task.Id,"rest on same task");});
   Test("备份恢复保留组关系及便签段落ID",()=>{var d=new AppData();var doc=GroupDocument();var n=GroupNote(d,doc);NoteTasks.Convert(d,n,doc);var copy=Store.Normalize(Store.Decode<AppData>(Store.Encode(d)));var nc=copy.Notes[0];var dc=NoteCodec.Decode(nc.Body);var ids=copy.Tasks.Select(t=>t.Id).ToArray();NoteTasks.Convert(copy,nc,dc);Assert(copy.Tasks.Select(t=>t.Id).SequenceEqual(ids)&&dc.Blocks[0].Id==doc.Blocks[0].Id,"round trip remains idempotent");});
   Test("旧段落无ID和重复ID可获得持久独立身份",()=>{var doc=GroupDocument();doc.Blocks[0].Id=null;doc.Blocks[2].Id=doc.Blocks[1].Id;var updated=NoteCodec.Decode(Store.Encode(doc));Assert(updated.Blocks.All(b=>!String.IsNullOrEmpty(b.Id))&&updated.Blocks.Select(b=>b.Id).Distinct().Count()==4,"repair paragraph IDs");Assert(NoteCodec.Decode(Store.Encode(updated)).Blocks.Select(b=>b.Id).SequenceEqual(updated.Blocks.Select(b=>b.Id)),"IDs stay persistent");});
  }
 }
}
