using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
namespace LittleTomato {
 public class FakeClock : ITimerClock {public double Value;public DateTime Now=new DateTime(2026,9,7,2,0,0,DateTimeKind.Utc);public double Seconds{get{return Value;}}public DateTime UtcNow{get{return Now;}}public void Add(double s){Value+=s;Now=Now.AddSeconds(s);}}
 public static class SelfTests {
  static List<string> report=new List<string>();static int passed,failed;
  static void Assert(bool condition,string name){if(!condition)throw new Exception(name);}
  static void Close(double a,double b,string msg){Assert(Math.Abs(a-b)<.02,msg+": "+a+" != "+b);}
  static Engine New(out FakeClock c){c=new FakeClock();var d=new AppData();var t=new Todo {Title="设计测试",Minutes=1};d.Tasks.Add(t);d.Selected=t.Id;return new Engine(d,c);}
  static void Advance(Engine e,FakeClock c,int seconds){for(int i=0;i<seconds;i++){c.Add(1);e.Tick();}}
  static void Test(string name,Action a){try{a();passed++;report.Add("PASS "+name);}catch(Exception ex){failed++;report.Add("FAIL "+name+" :: "+ex.Message);}}
  public static int Run(string output){
   Test("旧版本数据缺少便签仍可无损升级",()=>{var old=new AppData();old.Tasks.Add(new Todo{Title="保留任务"});string json=System.Text.RegularExpressions.Regex.Replace(Store.Encode(old),"\"Notes\":\\[\\],?","");var loaded=Store.Normalize(Store.Decode<AppData>(json));Assert(loaded.Notes!=null&&loaded.Notes.Count==0&&loaded.Tasks[0].Title=="保留任务","notes initialized without touching tasks");});
   Test("便签格式与勾选可序列化并恢复",()=>{var doc=new NoteDocument();doc.Blocks.Add(new NoteBlock{Kind="check",Done=true,Runs=new List<NoteRun>{new NoteRun{Text="测试便签",Bold=true,Italic=true,Strike=true,Highlight=true,Underline=true,Link="https://example.com"}}});var copy=NoteCodec.Decode(Store.Encode(doc));Assert(copy.Blocks[0].Done&&copy.Blocks[0].Runs[0].Bold&&copy.Blocks[0].Runs[0].Strike&&copy.Blocks[0].Runs[0].Highlight&&copy.PlainText=="测试便签","rich content preserved");});
   Test("便签链接仅允许网页地址",()=>{Assert(NoteCodec.SafeLink("https://example.com")&&!NoteCodec.SafeLink("file:///C:/test")&&!NoteCodec.SafeLink("javascript:alert(1)")&&!NoteCodec.SafeLink("cmd.exe"),"unsafe schemes blocked");});
   Test("便签回收站与标题规则保留在备份中",()=>{var data=new AppData();data.Notes.Add(new Note{PlainText="第一行\n第二行",Deleted=true,Pinned=true,Color="sage"});var copy=Store.Normalize(Store.Decode<AppData>(Store.Encode(data)));Assert(copy.Notes[0].Deleted&&copy.Notes[0].Pinned&&copy.Notes[0].DisplayTitle=="第一行","metadata and first-line title preserved");});
   Test("便签重复标识被拒绝而未知正文保留原文",()=>{var data=new AppData();data.Notes.Add(new Note{Id="same",Body="unreadable body"});data.Notes.Add(new Note{Id="same"});bool rejected=false;try{Store.Normalize(data);}catch(System.IO.InvalidDataException){rejected=true;}Assert(rejected,"duplicate rejected");data.Notes.RemoveAt(1);Assert(Store.Normalize(data).Notes[0].Body=="unreadable body","body never silently cleared");});

   Test("从当前任务的休息阶段重新开始会进入专注",()=>{FakeClock c;var e=New(out c);var task=e.Selected;e.Start(task);Advance(e,c,60);Assert(e.Data.Active.Kind=="short","break ready");e.Start(task);Assert(e.Data.Active.Kind=="focus"&&e.Data.Active.Running&&e.Data.Active.Duration==60&&e.Data.Active.Elapsed==0,"new focus instead of resuming break");Advance(e,c,7);e.Pause();e.Start(task);Assert(e.Data.Active.Running&&e.Data.Active.Elapsed==7,"existing focus resumes without resetting");});
   Test("多数据目录实例按唯一窗口标记定位",()=>{string a="TomoBar.Test."+Guid.NewGuid().ToString("N"),b="TomoBar.Test."+Guid.NewGuid().ToString("N");using(var first=new System.Windows.Forms.Form())using(var second=new System.Windows.Forms.Form()){var h1=first.Handle;var h2=second.Handle;try{Native.SetProp(h1,a,new IntPtr(1));Native.SetProp(h2,b,new IntPtr(1));Assert(Native.FindInstance(a)==h1&&Native.FindInstance(b)==h2,"separate windows with same generic title");Assert(Native.FindInstance("TomoBar.Unknown."+Guid.NewGuid().ToString("N"))==IntPtr.Zero,"missing instance stays missing");}finally{Native.RemoveProp(h1,a);Native.RemoveProp(h2,b);}}});

   Test("自启命令正确引用空格中文路径并在后台运行",()=>{string path=@"C:\应用 程序\小番茄.exe";Assert(StartupRegistration.CommandFor(path)=="\""+path+"\" --background","quoted executable and background flag");});
   Test("自启拒绝无效和过长的命令",()=>{foreach(string path in new[]{"relative.exe","C:\\bad\"path.exe","C:\\"+new string('a',260)+".exe"}){bool rejected=false;try{StartupRegistration.CommandFor(path);}catch(ArgumentException){rejected=true;}Assert(rejected,"invalid startup path rejected");}});
   Test("自启注册开关与路径更新仅修改自身条目",()=>{
    string keyPath=@"Software\LittleTomato\Tests\"+Guid.NewGuid().ToString("N");
    try{using(var key=Microsoft.Win32.Registry.CurrentUser.CreateSubKey(keyPath))key.SetValue("OtherApp","keep");
     var startup=new StartupRegistration(System.Reflection.Assembly.GetExecutingAssembly().Location,keyPath);Assert(!startup.IsRegistered,"default off");startup.SetEnabled(true);Assert(startup.IsRegistered&&startup.UsesCurrentPath,"registered current exe");
     using(var key=Microsoft.Win32.Registry.CurrentUser.OpenSubKey(keyPath,true)){Assert(key.GetValueKind(StartupRegistration.ValueName)==Microsoft.Win32.RegistryValueKind.String,"REG_SZ");key.SetValue(StartupRegistration.ValueName,"\"C:\\old folder\\app.exe\" --background");}
     Assert(startup.IsRegistered&&!startup.UsesCurrentPath,"old path detected");startup.SetEnabled(true);Assert(startup.UsesCurrentPath,"current path restored");startup.SetEnabled(true);startup.SetEnabled(false);startup.SetEnabled(false);Assert(!startup.IsRegistered,"idempotent disabling");
     using(var key=Microsoft.Win32.Registry.CurrentUser.OpenSubKey(keyPath))Assert((string)key.GetValue("OtherApp")=="keep","other startup entries untouched");
    }finally{Microsoft.Win32.Registry.CurrentUser.DeleteSubKey(keyPath,false);}
   });

   Test("新建计时和记录的时间字段默认为有效UTC",()=>{var a=new ActiveTimer();var s=new Session();Assert(a.StartUtc.Kind==DateTimeKind.Utc&&a.StartUtc.Year>2000,"timer default");Assert(s.StartUtc.Kind==DateTimeKind.Utc&&s.EndUtc.Kind==DateTimeKind.Utc,"record defaults");Store.Encode(a);Store.Encode(s);});
   Test("保存前修复MinValue并保留计时状态",()=>{FakeClock c;var e=New(out c);e.Data.Active=new ActiveTimer{TaskId=e.Selected.Id,Duration=60,Elapsed=17,Running=true,StartUtc=DateTime.MinValue};var restored=Store.Decode<AppData>(Store.Encode(e.Data));Assert(restored.Active.StartUtc.Kind==DateTimeKind.Utc&&restored.Active.StartUtc.Year>2000,"UTC date repaired");Assert(restored.Active.Elapsed==17&&restored.Active.Running&&restored.Active.TimestampRecovered,"state and recovery flag preserved");});
   Test("历史记录边界时间修复不丢任务时长",()=>{FakeClock c;var e=New(out c);var day=c.UtcNow.ToLocalTime().ToString("yyyy-MM-dd");e.Data.Sessions.Add(new Session{TaskId=e.Selected.Id,Title="保留记录",StartUtc=DateTime.MinValue,EndUtc=DateTime.SpecifyKind(DateTime.MaxValue,DateTimeKind.Local),Seconds=45,Days=new Dictionary<string,double>{{day,45}}});var d=Store.Decode<AppData>(Store.Encode(e.Data));Assert(d.Sessions.Count==1&&d.Sessions[0].Seconds==45&&d.Sessions[0].Days[day]==45,"original history retained");Assert(d.Sessions[0].TimestampRecovered&&d.Sessions[0].EndUtc.Kind==DateTimeKind.Utc,"boundary converted safely");});
   Test("旧JSON缺少时间字段可加载并再次保存",()=>{FakeClock c;var e=New(out c);e.Start(e.Selected);var json=System.Text.RegularExpressions.Regex.Replace(Store.Encode(e.Data),"\"StartUtc\":\"[^\"]*\",?","");var d=Store.Normalize(Store.Decode<AppData>(json));Assert(d.Active!=null&&d.Active.TimestampRecovered&&!d.Active.Running,"missing field repaired on load");Store.Encode(d);});
   Test("正常UTC时间保持原值且修复不重复发生",()=>{FakeClock c;var e=New(out c);e.Start(e.Selected);var before=e.Data.Active.StartUtc;Assert(Store.RepairTimestamps(e.Data,c.UtcNow)==0&&e.Data.Active.StartUtc==before,"valid timestamps unchanged");e.Data.Active.StartUtc=DateTime.MinValue;Assert(Store.RepairTimestamps(e.Data,c.UtcNow)==1,"first repair");Assert(Store.RepairTimestamps(e.Data,c.UtcNow)==0,"idempotent repair");});
   Test("保存提示区分数据转换与磁盘错误",()=>{var format=Program.SaveFailureMessage(new System.Runtime.Serialization.SerializationException("bad date"));Assert(!format.Contains("磁盘")&&format.Contains("转换"),"format error is not blamed on disk");Assert(Program.SaveFailureMessage(new IOException("disk full")).Contains("磁盘"),"IO error guidance");});
   Test("空清单一键生成默认任务并沿用默认时长",()=>{var c=new FakeClock();var d=new AppData();d.Settings.Focus=40;var e=new Engine(d,c);e.Start(e.EnsureFocusTask());Assert(d.Tasks.Count==1&&e.Current.Title==Engine.DefaultTaskTitle,"default task");Assert(d.Active.Running&&d.Active.Duration==2400,"starts with default minutes");e.End();e.Start(e.EnsureFocusTask());Assert(d.Tasks.Count==1,"reuse current default task");});
   Test("快速开始优先选中任务并排除完成归档任务",()=>{FakeClock c;var e=New(out c);var chosen=new Todo{Title="指定任务"};e.Data.Tasks.Add(chosen);e.Data.Selected=chosen.Id;Assert(e.EnsureFocusTask()==chosen,"respect selection");chosen.Done=true;e.Data.Tasks[0].Archived=true;var quick=e.EnsureFocusTask();Assert(quick.Title==Engine.DefaultTaskTitle&&!quick.Done&&!quick.Archived,"fresh task after all done");});
   Test("真实 Windows 单调时钟可用",()=>{var clock=new TimerClock();double before=clock.Seconds;System.Threading.Thread.Sleep(120);double elapsed=clock.Seconds-before;Assert(elapsed>=.08&&elapsed<2,"native awake clock");});
   Test("实际时长、暂停排除与提前结束",()=>{FakeClock c;var e=New(out c);var t=e.Selected;e.Start(t);Advance(e,c,17);e.Pause();Advance(e,c,30);Close(e.Total(t.Id),17,"paused time");e.Resume();Advance(e,c,4);e.End();Close(e.Total(t.Id),21,"partial duration");Assert(e.Data.Sessions.Count==1&&!e.Data.Sessions[0].Complete,"partial record");Assert(e.Count(t.Id)==0,"partial count");});
   Test("完整番茄进入暂停的短休息",()=>{FakeClock c;var e=New(out c);var t=e.Selected;e.Start(t);Advance(e,c,60);Assert(e.Count(t.Id)==1,"complete count");Assert(e.Data.Active.Kind=="short"&&!e.Data.Active.Running,"manual break");Close(e.Total(t.Id),60,"focus only");e.Resume();Advance(e,c,45);e.End();Close(e.Total(t.Id),60,"break excluded");});
   Test("每四轮进入长休息且不自动开始",()=>{FakeClock c;var e=New(out c);var t=e.Selected;for(int i=0;i<4;i++){e.Start(t);Advance(e,c,60);Assert(e.Data.Active.Kind==(i==3?"long":"short"),"break kind");Assert(!e.Data.Active.Running,"manual transition");e.End();}Assert(e.Count(t.Id)==4,"four rounds");});
   Test("切换任务保存旧任务且只运行一个",()=>{FakeClock c;var e=New(out c);var a=e.Selected;var b=new Todo{Title="另一个任务"};e.Data.Tasks.Add(b);e.Start(a);Advance(e,c,12);e.Start(b);Advance(e,c,7);Close(e.Total(a.Id),12,"old task");Close(e.Total(b.Id),7,"new task");Assert(e.Data.Active.TaskId==b.Id&&e.Data.Sessions.Count==1,"single active");});
   Test("完成任务保存进行中的专注",()=>{FakeClock c;var e=New(out c);var t=e.Selected;e.Start(t);Advance(e,c,9);e.MarkDone(t);Assert(t.Done&&e.Data.Active==null,"done state");Close(e.Total(t.Id),9,"done retains time");});
   Test("崩溃恢复保持暂停，不计入离线时间",()=>{FakeClock c;var e=New(out c);e.Start(e.Selected);Advance(e,c,23);var d=Store.Normalize(Store.Decode<AppData>(Store.Encode(e.Data)));c.Add(36000);var recovered=new Engine(d,c);Assert(!d.Active.Running,"paused recovery");recovered.Tick();Close(d.Active.Elapsed,23,"no offline accumulation");});
   Test("休眠或长消息间隔自动暂停",()=>{FakeClock c;var e=New(out c);e.Start(e.Selected);Advance(e,c,4);c.Add(3600);e.Tick();Assert(!e.Data.Active.Running,"long gap pause");Close(e.Data.Active.Elapsed,4,"long gap excluded");});
   Test("跨午夜按日期拆分",()=>{FakeClock c;var e=New(out c);c.Now=new DateTime(2026,9,7,23,59,55,DateTimeKind.Local).ToUniversalTime();e.Start(e.Selected);Advance(e,c,10);Close(e.DayTotal(new DateTime(2026,9,7)),5,"yesterday");Close(e.DayTotal(new DateTime(2026,9,8)),5,"today");});
   Test("暂停跨天恢复无重复归属",()=>{FakeClock c;var e=New(out c);c.Now=new DateTime(2026,9,7,23,59,50,DateTimeKind.Local).ToUniversalTime();e.Start(e.Selected);Advance(e,c,5);e.Pause();c.Add(30);e.Resume();Advance(e,c,5);e.End();Close(e.DayTotal(new DateTime(2026,9,7)),5,"before pause");Close(e.DayTotal(new DateTime(2026,9,8)),5,"after pause");});
   Test("系统时钟调整不影响剩余时间",()=>{FakeClock c;var e=New(out c);e.Start(e.Selected);Advance(e,c,10);c.Now=c.Now.AddHours(-3);Advance(e,c,5);Assert(e.Remaining==45,"monotonic countdown");});
   Test("结束时恰好到点不重复入账",()=>{FakeClock c;var e=New(out c);var t=e.Selected;e.Start(t);Advance(e,c,59);c.Add(1);e.End();Assert(e.Data.Sessions.Count==1&&e.Count(t.Id)==1,"exact completion");Close(e.Total(t.Id),60,"once only");});
   Test("中文序列化与原子备份恢复",()=>{string dir=Path.Combine(Path.GetDirectoryName(Path.GetFullPath(output)),"persistence-test-"+Guid.NewGuid().ToString("N"));var store=new Store(dir);var d=new AppData();d.Tasks.Add(new Todo{Title="中文 🍅 引号 \" 与换行\n任务"});store.Save(d);d.Tasks.Add(new Todo{Title="第二项"});store.Save(d);Assert(store.Load().Tasks.Count==2,"save load");File.WriteAllText(store.FilePath,"broken");var recovered=store.Load();Assert(recovered.Tasks.Count==1&&recovered.Tasks[0].Title.Contains("中文"),"backup recovery");Assert(Directory.GetFiles(dir,"*.damaged-*").Length==1,"corrupt original retained");});
   Test("损坏主文件与备份不能静默清空",()=>{string dir=Path.Combine(Path.GetDirectoryName(Path.GetFullPath(output)),"corrupt-test-"+Guid.NewGuid().ToString("N"));var store=new Store(dir);File.WriteAllText(store.FilePath,"broken");bool thrown=false;try{store.Load();}catch(IOException){thrown=true;}Assert(thrown,"must stop data loss");});
   Test("拒绝不支持的备份版本和重复任务 ID",()=>{var d=new AppData{Version=2};bool thrown=false;try{Store.Normalize(d);}catch(InvalidDataException){thrown=true;}Assert(thrown,"version rejected");d=new AppData();var a=new Todo{Title="A"};d.Tasks.Add(a);d.Tasks.Add(new Todo{Id=a.Id,Title="B"});thrown=false;try{Store.Normalize(d);}catch(InvalidDataException){thrown=true;}Assert(thrown,"duplicate id rejected");});
   Test("设置范围与无效计时恢复",()=>{var d=new AppData();d.Settings.Focus=0;d.Settings.Rounds=999;d.Active=new ActiveTimer {TaskId="missing",Duration=60};Store.Normalize(d);Assert(d.Settings.Focus==1&&d.Settings.Rounds==12&&d.Active==null,"clamped and invalid discarded");});
   Test("秒级显示与大于一小时的任务",()=>{FakeClock c;var e=New(out c);e.Selected.Minutes=120;e.Start(e.Selected);Assert(e.DisplayTime=="120:00","long task format");c.Add(.5);e.Tick();Assert(e.DisplayTime=="120:00","ceiling subsecond");});
   report.Add("\n"+passed+" passed; "+failed+" failed");File.WriteAllLines(output,report,System.Text.Encoding.UTF8);return failed==0?0:1;
  }
 }
}
