using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Shapes;
using System.Windows.Shell;
using System.Windows.Interop;
using System.Windows.Automation;
using Microsoft.Win32;

namespace LittleTomato {
 public static class UI {
  public static Brush Brush(string key) {return (Brush)Application.Current.FindResource(key);}
  public static TextBlock Text(string text,double size,string color) {var t=new TextBlock {Text=text,FontSize=size};t.SetResourceReference(TextBlock.ForegroundProperty,color);return t;}
  public static TextBlock Label(string text) {var t=Text(text,12,"Muted");t.Margin=new Thickness(0,0,0,8);return t;}
  public static Button Button(string text,Action action,bool primary) {var b=new Button {Content=text};if(primary){b.SetResourceReference(Control.BackgroundProperty,"Accent");b.SetResourceReference(Control.ForegroundProperty,"OnAccent");}b.Click+=(s,e)=>action();AutomationProperties.SetName(b,text);return b;}
  public static void IconLabel(Button button,string label,string icon) {
   string state=icon+label;if(String.Equals(button.Tag,state))return;button.Tag=state;
   string stroke=icon=="chevron-right"?"M6,3 L11,8 L6,13":icon=="chevron-down"?"M3,6 L8,11 L13,6":icon=="pin"?"M5,2 L11,2 M6,2 L6,7 L3,10 L13,10 L10,7 L10,2 M8,10 L8,15":icon=="notes"?"M3,2 L13,2 L13,11 L10,14 L3,14 Z M10,14 L10,11 L13,11 M5,5 L11,5 M5,8 L10,8":icon=="tasks"?"M2,4 L4,6 L7,2 M9,4 L15,4 M2,11 L4,13 L7,9 M9,11 L15,11":icon=="stats"?"M2,14 L2,9 M7,14 L7,5 M12,14 L12,2":icon=="settings"?"M2,4 L15,4 M2,12 L15,12 M6,2 L6,6 M11,10 L11,14":icon=="minimize"?"M3,8 L13,8":icon=="maximize"?"M3,3 L13,3 L13,13 L3,13 Z":icon=="restore"?"M5,3 L13,3 L13,11 M3,5 L11,5 L11,13 L3,13 Z":icon=="plus"?"M8,3 L8,13 M3,8 L13,8":icon=="more"?"M3,8 L3.1,8 M8,8 L8.1,8 M13,8 L13.1,8":icon=="undo"?"M6,3 L2,7 L6,11 M2,7 L10,7 Q14,7 14,12":null;
   string data=stroke??(icon=="pause"?"M4,2 L7,2 L7,14 L4,14 Z M10,2 L13,2 L13,14 L10,14 Z":icon=="play"?"M4,2 L14,8 L4,14 Z":icon=="stop"?"M3,3 L13,3 L13,13 L3,13 Z":icon=="open"?"M5,2 L14,2 L14,11 L12,11 L12,5 L3,14 L2,13 L11,4 L5,4 Z":icon=="close"?"M3,2 L8,7 L13,2 L14,3 L9,8 L14,13 L13,14 L8,9 L3,14 L2,13 L7,8 L2,3 Z":"M3,5 L8,10 L13,5 L14,6 L8,12 L2,6 Z");
   var glyph=new System.Windows.Shapes.Path {Data=Geometry.Parse(data),Width=16,Height=16,Stretch=Stretch.Uniform,VerticalAlignment=VerticalAlignment.Center};if(stroke==null)glyph.SetBinding(Shape.FillProperty,new System.Windows.Data.Binding("Foreground"){Source=button});else {glyph.StrokeThickness=1.5;glyph.StrokeStartLineCap=PenLineCap.Round;glyph.StrokeEndLineCap=PenLineCap.Round;glyph.StrokeLineJoin=PenLineJoin.Round;glyph.SetBinding(Shape.StrokeProperty,new System.Windows.Data.Binding("Foreground"){Source=button});}
   var row=new StackPanel {Orientation=Orientation.Horizontal,HorizontalAlignment=button.HorizontalContentAlignment};row.Children.Add(glyph);if(label.Length>0)row.Children.Add(new TextBlock {Text=label,Margin=new Thickness(9,0,0,0),VerticalAlignment=VerticalAlignment.Center});button.Content=row;AutomationProperties.SetName(button,label.Length>0?label:"关闭面板");
  }
  public static Border Card(UIElement child,Thickness padding) {var b=new Border {CornerRadius=new CornerRadius(16),Padding=padding,Child=child,BorderThickness=new Thickness(1)};b.SetResourceReference(Border.BackgroundProperty,"Card");b.SetResourceReference(Border.BorderBrushProperty,"Line");return b;}
  public static StackPanel Stack(params UIElement[] elements) {var s=new StackPanel();foreach(var e in elements)s.Children.Add(e);return s;}
  public static StackPanel Row(params UIElement[] elements) {var s=Stack(elements);s.Orientation=Orientation.Horizontal;return s;}
  public static void At(Grid grid,UIElement element,int row,int col) {Grid.SetRow(element,row);Grid.SetColumn(element,col);grid.Children.Add(element);}
  public static Grid Columns(params double[] widths) {var g=new Grid();foreach(var w in widths)g.ColumnDefinitions.Add(new ColumnDefinition {Width=w<0?new GridLength(-w,GridUnitType.Star):new GridLength(w)});return g;}
  public static FrameworkElement Tomato(double size) {var v=new Viewbox {Width=size,Height=size};var g=new Grid {Width=32,Height=32};g.Children.Add(new Ellipse {Width=26,Height=23,Margin=new Thickness(3,8,3,1),Fill=new SolidColorBrush(Color.FromRgb(222,102,87))});g.Children.Add(new System.Windows.Shapes.Path {Data=Geometry.Parse("M16,12 L7,6 L14,7 L16,1 L19,7 L26,5 L22,12 L17,10 Z"),Fill=new SolidColorBrush(Color.FromRgb(85,127,91))});g.Children.Add(new System.Windows.Shapes.Path {Data=Geometry.Parse("M9,16 Q6,21 10,24"),Stroke=new SolidColorBrush(Color.FromArgb(135,255,255,255)),StrokeThickness=2,StrokeStartLineCap=PenLineCap.Round,StrokeEndLineCap=PenLineCap.Round});v.Child=g;return v;}
  public static void Chrome(Window w) {
   w.WindowStyle=WindowStyle.None;w.ResizeMode=ResizeMode.CanResize;WindowChrome.SetWindowChrome(w,new WindowChrome {CaptionHeight=44,ResizeBorderThickness=new Thickness(6),CornerRadius=new CornerRadius(12),GlassFrameThickness=new Thickness(0),UseAeroCaptionButtons=false});
   w.SourceInitialized+=(s,e)=>{int round=2;Native.DwmSetWindowAttribute(new WindowInteropHelper(w).Handle,33,ref round,4);};
  }
  public static Grid Titlebar(Window w,string title,bool maximize) {
   var g=Columns(-1,42,maximize?42:0,42);g.Height=44;g.Margin=new Thickness(16,0,4,0);
   var label=Text(title,12,"Muted");label.VerticalAlignment=VerticalAlignment.Center;At(g,label,0,0);
   var min=Button("−",()=>w.WindowState=WindowState.Minimized,false);var max=Button("□",()=>w.WindowState=w.WindowState==WindowState.Maximized?WindowState.Normal:WindowState.Maximized,false);var close=Button("×",()=>w.Close(),false);
   IconLabel(min,"","minimize");IconLabel(max,"","maximize");IconLabel(close,"","close");AutomationProperties.SetName(min,"最小化");AutomationProperties.SetName(max,"最大化");AutomationProperties.SetName(close,"收起窗口");w.StateChanged+=(s,e)=>{IconLabel(max,"",w.WindowState==WindowState.Maximized?"restore":"maximize");AutomationProperties.SetName(max,w.WindowState==WindowState.Maximized?"还原窗口":"最大化");};
   foreach(var b in new[]{min,max,close}){var icon=(FrameworkElement)((StackPanel)b.Content).Children[0];icon.Width=12;icon.Height=12;b.FontSize=18;b.Padding=new Thickness(0);b.Background=Brushes.Transparent;WindowChrome.SetIsHitTestVisibleInChrome(b,true);}
   min.ToolTip="最小化到计时条";close.ToolTip="隐藏窗口，继续计时";At(g,min,0,1);if(maximize)At(g,max,0,2);At(g,close,0,3);return g;
  }
  public static Window Dialog(Window owner,string title,int width,int height) {return new Window {Owner=owner,Title=title,Width=width,Height=height,ResizeMode=ResizeMode.NoResize,WindowStartupLocation=WindowStartupLocation.CenterOwner,ShowInTaskbar=false};}
  public static TextBox Input(string name,string value) {var t=new TextBox {Text=value};AutomationProperties.SetName(t,name);return t;}
  public static void Notice(Window owner,string text) {MessageBox.Show(owner,text,"小番茄",MessageBoxButton.OK,MessageBoxImage.Information);}
 }
 public class ProgressRing : FrameworkElement {
  public double Progress;public bool Paused,Resting;
  protected override void OnRender(DrawingContext dc) {base.OnRender(dc);double r=Math.Min(ActualWidth,ActualHeight)/2-9;var c=new Point(ActualWidth/2,ActualHeight/2);dc.DrawEllipse(null,new Pen(UI.Brush("Soft"),7),c,r,r);double p=Math.Max(0,Math.Min(.999999,Progress));if(p<=0)return;double a=p*Math.PI*2;var geom=new StreamGeometry();using(var ctx=geom.Open()){ctx.BeginFigure(new Point(c.X,c.Y-r),false,false);ctx.ArcTo(new Point(c.X+Math.Sin(a)*r,c.Y-Math.Cos(a)*r),new Size(r,r),0,p>.5,SweepDirection.Clockwise,true,false);}var pen=new Pen(UI.Brush(Paused?"Muted":Resting?"Green":"Accent"),7){StartLineCap=PenLineCap.Round,EndLineCap=PenLineCap.Round};dc.DrawGeometry(null,pen,geom);}
 }
 public partial class MainWindow : Window {
  Program app;Grid content;Grid taskOverlay;Dictionary<string,Button> nav=new Dictionary<string,Button>();Dictionary<string,TextBlock> taskTotals=new Dictionary<string,TextBlock>();public string Page="tasks";string filter="todo";StackPanel taskList;TextBlock time,phase,current,rounds,today;Button toggle,end;ProgressRing ring;TextBlock countLabel;string search="";
  public MainWindow(Program owner) {
   app=owner;Style=(Style)Application.Current.FindResource(typeof(Window));UseLayoutRounding=true;Title="小番茄 · 专注每一刻";Width=Math.Max(680,Math.Min(1020,SystemParameters.WorkArea.Width-24));Height=Math.Max(440,Math.Min(750,SystemParameters.WorkArea.Height-24));MinWidth=Math.Min(760,Width);MinHeight=Math.Min(480,Height);WindowStartupLocation=WindowStartupLocation.CenterScreen;UI.Chrome(this);if(app.IconSource!=null)Icon=app.IconSource;
   var root=new Grid();root.RowDefinitions.Add(new RowDefinition {Height=new GridLength(44)});root.RowDefinitions.Add(new RowDefinition());root.Children.Add(UI.Titlebar(this,"小番茄",true));
   var body=UI.Columns(170,-1);Grid.SetRow(body,1);root.Children.Add(body);
   var side=new Grid {Margin=new Thickness(22,22,20,20)};side.RowDefinitions.Add(new RowDefinition {Height=GridLength.Auto});side.RowDefinitions.Add(new RowDefinition());side.RowDefinitions.Add(new RowDefinition {Height=GridLength.Auto});
   var brand=UI.Row(UI.Tomato(29),UI.Text("小番茄",19,"Ink"));((TextBlock)brand.Children[1]).Margin=new Thickness(9,0,0,0);((TextBlock)brand.Children[1]).FontWeight=FontWeights.SemiBold;side.Children.Add(brand);
   var links=new StackPanel {Margin=new Thickness(0,40,0,0)};UI.At(side,links,1,0);
   AddNav(links,"tasks","我的任务");AddNav(links,"stats","时间统计");AddNav(links,"notes","便签");AddNav(links,"settings","设置");
   var bottom=UI.Stack(UI.Text("把时间留给",12,"Muted"),UI.Text("真正重要的事。",12,"Muted"),UI.Text("本地保存 · 离线可用",10,"Muted"));foreach(FrameworkElement el in bottom.Children)el.Margin=new Thickness(0,0,0,7);UI.At(side,bottom,2,0);UI.At(body,side,0,0);
   content=new Grid {Margin=new Thickness(14,18,28,24)};UI.At(body,content,0,1);Content=root;
   Closing+=(s,e)=>{if(!app.Quitting){e.Cancel=true;Hide();app.ShowTrayHint();}};
   StateChanged+=(s,e)=>{if(WindowState==WindowState.Minimized)Hide();};
   PreviewKeyDown+=(s,e)=>{if(e.Key==Key.Escape&&Page=="notes"&&notesPage!=null&&notesPage.IsEditingTitle)return;if(e.Key==Key.N && Keyboard.Modifiers==ModifierKeys.Control){if(Page=="notes")app.Notes.New();else EditTask(null);e.Handled=true;}if(e.Key==Key.Escape){if(taskOverlay!=null)CloseEditor();else Hide();e.Handled=true;}};
   ShowPage("tasks");
  }
  void AddNav(StackPanel parent,string key,string text) {var b=UI.Button(text,()=>ShowPage(key),false);b.HorizontalContentAlignment=HorizontalAlignment.Left;b.Margin=new Thickness(0,0,0,8);b.Padding=new Thickness(13,13,8,13);UI.IconLabel(b,text,key);parent.Children.Add(b);nav[key]=b;}
  public void ShowPage(string page) {Page=page;foreach(var pair in nav){pair.Value.SetResourceReference(Control.BackgroundProperty,pair.Key==page?"Tint":"Bg");pair.Value.SetResourceReference(Control.ForegroundProperty,pair.Key==page?"Accent":"Muted");}content.Children.Clear();if(page=="tasks")BuildTasks();else if(page=="stats")BuildStats();else if(page=="notes")BuildNotes();else BuildSettings();}
  public void ModelChanged() {if(Page=="tasks"){FillTasks();RefreshTimer();}else if(Page=="stats")BuildStats();}
  Grid Header(string title,string subtitle,Button button) {var g=UI.Columns(-1,130);var t=UI.Text(title,26,"Ink");t.FontWeight=FontWeights.SemiBold;var s=UI.Text(subtitle,12,"Muted");s.Margin=new Thickness(0,9,0,0);g.Children.Add(UI.Stack(t,s));if(button!=null){button.VerticalAlignment=VerticalAlignment.Center;UI.At(g,button,0,1);}g.Margin=new Thickness(0,0,0,25);return g;}
  Button NewTaskButton(){var b=UI.Button("新建任务",()=>EditTask(null),true);UI.IconLabel(b,"新建任务","plus");return b;}
  void BuildTasks() {
   var root=new Grid();root.RowDefinitions.Add(new RowDefinition {Height=GridLength.Auto});root.RowDefinitions.Add(new RowDefinition());content.Children.Add(root);
   root.Children.Add(Header("今天，专注一件事。",DateTime.Now.ToString("M月d日 dddd")+"  ·  每一点投入，都算数",NewTaskButton()));
   var cols=UI.Columns(-1,20,302);UI.At(root,cols,1,0);
   var left=new Grid();left.RowDefinitions.Add(new RowDefinition {Height=GridLength.Auto});left.RowDefinitions.Add(new RowDefinition {Height=GridLength.Auto});left.RowDefinitions.Add(new RowDefinition());left.RowDefinitions.Add(new RowDefinition {Height=GridLength.Auto});UI.At(cols,left,0,0);
   var filters=UI.Row();foreach(var f in new[]{"todo","done","archive"}){string id=f;var b=UI.Button(f=="todo"?"待办":f=="done"?"已完成":"已归档",()=>{filter=id;ShowPage("tasks");},false);b.Padding=new Thickness(12,7,12,7);b.Margin=new Thickness(0,0,6,0);b.SetResourceReference(Control.BackgroundProperty,f==filter?"Soft":"Bg");b.SetResourceReference(Control.ForegroundProperty,f==filter?"Ink":"Muted");filters.Children.Add(b);}UI.At(left,filters,0,0);
   var box=UI.Input("搜索任务",search);box.ToolTip="搜索任务";var searchGrid=new Grid {Margin=new Thickness(0,13,0,13)};searchGrid.Children.Add(box);var placeholder=UI.Text("搜索任务…",12,"Muted");placeholder.Margin=new Thickness(13,0,0,0);placeholder.VerticalAlignment=VerticalAlignment.Center;placeholder.IsHitTestVisible=false;placeholder.Visibility=String.IsNullOrEmpty(search)?Visibility.Visible:Visibility.Collapsed;searchGrid.Children.Add(placeholder);box.TextChanged+=(s,e)=>{search=box.Text;placeholder.Visibility=String.IsNullOrEmpty(search)?Visibility.Visible:Visibility.Collapsed;FillTasks();};UI.At(left,searchGrid,1,0);
   taskList=new StackPanel();var scroll=new ScrollViewer {Content=taskList,Padding=new Thickness(0,0,4,0)};UI.At(left,scroll,2,0);
   countLabel=UI.Text("",11,"Muted");countLabel.Margin=new Thickness(2,15,0,0);UI.At(left,countLabel,3,0);
   var focus=new StackPanel();var badge=UI.Text("此刻，只管专注",12,"Muted");badge.HorizontalAlignment=HorizontalAlignment.Center;badge.Margin=new Thickness(0,2,0,16);focus.Children.Add(badge);
   current=UI.Text("自由专注",17,"Ink");current.TextTrimming=TextTrimming.CharacterEllipsis;current.TextAlignment=TextAlignment.Center;current.FontWeight=FontWeights.SemiBold;current.Margin=new Thickness(0,0,0,16);focus.Children.Add(current);
   var face=new Grid {Width=226,Height=226};ring=new ProgressRing();face.Children.Add(ring);var digits=new StackPanel {VerticalAlignment=VerticalAlignment.Center};phase=UI.Text("准备专注",12,"Muted");phase.HorizontalAlignment=HorizontalAlignment.Center;time=UI.Text("25:00",48,"Ink");time.FontFamily=new FontFamily("Segoe UI");Typography.SetNumeralAlignment(time,FontNumeralAlignment.Tabular);time.FontWeight=FontWeights.Normal;time.HorizontalAlignment=HorizontalAlignment.Center;rounds=UI.Text("第 1 个番茄",11,"Muted");rounds.HorizontalAlignment=HorizontalAlignment.Center;digits.Children.Add(phase);digits.Children.Add(time);digits.Children.Add(rounds);face.Children.Add(digits);focus.Children.Add(face);
   toggle=UI.Button("开始专注",TogglePreview,true);toggle.Margin=new Thickness(3,19,3,9);toggle.Height=44;focus.Children.Add(toggle);end=UI.Button("结束并保存",()=>app.EndTimer(),false);end.Margin=new Thickness(3,0,3,18);focus.Children.Add(end);
   today=UI.Text("",12,"Muted");today.TextAlignment=TextAlignment.Center;focus.Children.Add(today);
   var card=UI.Card(focus,new Thickness(22));card.VerticalAlignment=VerticalAlignment.Top;UI.At(cols,new ScrollViewer {Content=card,Padding=new Thickness(0,0,5,0)},0,2);FillTasks();RefreshTimer();
  }
  void FillTasks() {
   if(taskList==null || Page!="tasks")return;taskList.Children.Clear();taskTotals.Clear();taskCards.Clear();var list=VisibleTaskTree();
   if(list.Count==0) {var icon=UI.Tomato(48);icon.Opacity=.8;var title=UI.Text(String.IsNullOrEmpty(search)?(filter=="todo"?"从一件小事开始":"这里还没有任务"):"没有找到匹配的任务",17,"Ink");title.TextAlignment=TextAlignment.Center;title.Margin=new Thickness(0,20,0,8);var sub=UI.Text(filter=="todo"?"直接点击开始专注，任务名称可以稍后再改。":"完成与归档的任务会保留时间记录。",11,"Muted");sub.TextAlignment=TextAlignment.Center;sub.TextWrapping=TextWrapping.Wrap;var empty=UI.Stack(icon,title,sub);empty.Margin=new Thickness(12,58,12,0);taskList.Children.Add(empty);}
   foreach(var task in list) {
    var t=task;var g=UI.Columns(26,-1,42);var check=new CheckBox {IsChecked=t.Done,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(0)};check.ToolTip=t.Done?"重新设为待办":"标记完成";AutomationProperties.SetName(check,(t.Done?"恢复任务 ":"完成任务 ")+t.Title);check.Click+=(s,e)=>app.Engine.MarkDone(t);if(!t.Archived&&!t.IsGroup)UI.At(g,check,0,0);if(t.IsGroup){var fold=UI.Button(collapsedGroups.Contains(t.Id)?"›":"⌄",()=>{if(!collapsedGroups.Add(t.Id))collapsedGroups.Remove(t.Id);FillTasks();},false);UI.IconLabel(fold,"",collapsedGroups.Contains(t.Id)?"chevron-right":"chevron-down");var chevron=(FrameworkElement)((StackPanel)fold.Content).Children[0];chevron.Width=11;chevron.Height=11;fold.Padding=new Thickness(0);fold.Width=24;fold.Background=Brushes.Transparent;fold.ToolTip="展开 / 收起任务组";AutomationProperties.SetName(fold,"折叠任务组 "+t.Title);UI.At(g,fold,0,0);}
    var title=UI.Text((TaskDepth(t)>1?"↳  ":"")+t.Title,14,"Ink");title.FontWeight=FontWeights.Medium;title.TextTrimming=TextTrimming.CharacterEllipsis;title.ToolTip=t.Title;
    var sub=UI.Text(t.IsGroup?GroupProgress(t):t.Minutes+" 分钟 / 轮  ·  "+app.Engine.Count(t.Id)+" / "+t.Planned+" 个",11,"Muted");sub.Margin=new Thickness(0,7,0,0);var total=UI.Text(TaskTotalLabel(t),11,"Muted");taskTotals[t.Id]=total;total.Margin=new Thickness(0,4,0,0);var text=UI.Stack(title,sub,total);text.VerticalAlignment=VerticalAlignment.Center;text.Margin=new Thickness(0,0,7,0);UI.At(g,text,0,1);
    var action=UI.Button(t.Archived?"↶":t.Done?"···":"▶",()=>{if(t.Archived){foreach(var restored in t.IsGroup?NoteTasks.Branch(app.Data,t):new List<Todo>{t})restored.Archived=false;app.Engine.Signal();}else if(t.Done)EditTask(t);else{if(app.Data.Active!=null&&app.Data.Active.TaskId==t.Id&&app.Data.Active.Running&&app.Data.Active.Kind=="focus")app.ToggleTimer();else app.StartTask(t);}},false);action.Padding=new Thickness(0);action.Height=34;action.Width=34;UI.IconLabel(action,"",t.Archived?"undo":t.Done?"more":app.Data.Active!=null&&app.Data.Active.TaskId==t.Id&&app.Data.Active.Running&&app.Data.Active.Kind=="focus"?"pause":"play");bool canPause=app.Data.Active!=null&&app.Data.Active.TaskId==t.Id&&app.Data.Active.Running&&app.Data.Active.Kind=="focus";action.ToolTip=t.Archived?"取消归档":t.Done?"查看任务":canPause?"暂停专注":"开始 / 继续";AutomationProperties.SetName(action,(t.Archived?"取消归档 ":t.Done?"查看任务 ":canPause?"暂停任务 ":"开始任务 ")+t.Title);action.SetResourceReference(Control.BackgroundProperty,"Tint");action.SetResourceReference(Control.ForegroundProperty,"Accent");UI.At(g,action,0,2);
    var card=UI.Card(g,new Thickness(13,15,9,15));card.Margin=new Thickness(TaskDepth(t)*20,0,0,t.IsGroup?6:8);if(t.IsGroup){card.SetResourceReference(Border.BackgroundProperty,"Soft");title.FontWeight=FontWeights.SemiBold;}taskCards[t.Id]=card;AutomationProperties.SetName(card,"预览任务 "+t.Title);if(PreviewedTask!=null&&PreviewedTask.Id==t.Id)card.SetResourceReference(Border.BorderBrushProperty,"Accent");card.MouseLeftButtonDown+=(s,e)=>{PreviewTask(t);if(e.ClickCount==2){if(t.IsGroup)OpenSourceNote(t);else EditTask(t);e.Handled=true;}};
    var menu=new ContextMenu();if(t.SourceNoteId!=null)AddMenu(menu,"打开来源便签",()=>OpenSourceNote(t));AddMenu(menu,t.IsGroup?"编辑组名（便签标题）":"编辑任务",()=>{if(t.IsGroup){ShowPage("notes");}else EditTask(t);});AddMenu(menu,"查看专注记录",()=>TaskHistory(t));AddMenu(menu,"上移",()=>{int i=app.Data.Tasks.IndexOf(t);if(i>0){app.Data.Tasks.RemoveAt(i);app.Data.Tasks.Insert(i-1,t);app.Engine.Signal();}});AddMenu(menu,"下移",()=>{int i=app.Data.Tasks.IndexOf(t);if(i<app.Data.Tasks.Count-1){app.Data.Tasks.RemoveAt(i);app.Data.Tasks.Insert(i+1,t);app.Engine.Signal();}});AddMenu(menu,t.Archived?"取消归档":"归档任务",()=>{var targets=t.IsGroup?NoteTasks.Branch(app.Data,t):new List<Todo>{t};if(app.Data.Active!=null&&targets.Any(x=>x.Id==app.Data.Active.TaskId))app.Engine.End();bool archive=!t.Archived;foreach(var target in targets)target.Archived=archive;app.Engine.Signal();});card.ContextMenu=menu;if(t.IsGroup){action.ToolTip="开始组内下一项待办";action.IsEnabled=NoteTasks.Next(app.Data,t)!=null;AutomationProperties.SetName(action,"开始任务组 "+t.Title);}taskList.Children.Add(card);
   }
   if(countLabel!=null)countLabel.Text=list.Count(t=>!t.IsGroup)+" 项任务  ·  单击预览，点击播放开始专注";
  }
  static void AddMenu(ContextMenu menu,string text,Action action) {var m=new MenuItem {Header=text};m.Click+=(s,e)=>action();menu.Items.Add(m);}
  string previewTaskId;readonly Dictionary<string,Border> taskCards=new Dictionary<string,Border>();
  public Todo PreviewedTask {get{return app.Data.Tasks.FirstOrDefault(t=>t.Id==previewTaskId)??app.Engine.Current;}}
  public void PreviewTask(Todo task){previewTaskId=task==null?null:task.Id;RefreshTimer();}
  public void ClearTaskPreview(){previewTaskId=null;RefreshTimer();}
  void TogglePreview(){var task=PreviewedTask;if(task!=null&&task.IsGroup){app.StartTask(task);return;}if(task!=null&&(task.Done||task.Archived))return;if(task!=null&&(app.Data.Active==null||app.Data.Active.TaskId!=task.Id))app.StartTask(task);else app.ToggleTimer();}
  public void RefreshTimer() {
   if(Page!="tasks" || time==null)return;var actual=app.Data.Active;var task=PreviewedTask;bool preview=task!=null&&(actual==null||actual.TaskId!=task.Id);var a=preview?null:actual;
   time.Text=preview?String.Format("{0:00}:00",task.Minutes):app.Engine.DisplayTime;current.Text=task==null?"自由专注":task.Title;current.ToolTip=current.Text;phase.Text=preview?"任务预览":app.Engine.Phase+(a!=null&&!a.Running?" · 已暂停":"");
   rounds.Text=preview?(actual!=null?(actual.Running?"正在计时：":"已暂停：")+(app.Engine.Current==null?"当前任务":app.Engine.Current.Title):"点击开始，进入这项任务"):"本组第 "+(app.Data.Cycle%app.Data.Settings.Rounds+1)+" / "+app.Data.Settings.Rounds+" 个番茄";rounds.TextTrimming=TextTrimming.CharacterEllipsis;rounds.MaxWidth=218;rounds.ToolTip=rounds.Text;
   if(a!=null && a.Kind!="focus")rounds.Text="休息也很重要";
   foreach(var pair in taskTotals)pair.Value.Text=TaskTotalLabel(app.Data.Tasks.First(t=>t.Id==pair.Key));foreach(var pair in taskCards)pair.Value.SetResourceReference(Border.BorderBrushProperty,task!=null&&task.Id==pair.Key?"Accent":"Line");
   UI.IconLabel(toggle,preview&&actual!=null?"切换并开始":a==null?"开始专注":a.Running?"暂停":a.Elapsed==0&&a.Kind!="focus"?"开始休息":a.Kind=="focus"?"继续专注":"继续休息",a!=null&&a.Running?"pause":"play");toggle.IsEnabled=task==null||!task.Done&&!task.Archived;end.Content=a!=null&&a.Kind!="focus"?"跳过休息":"结束并保存";end.IsEnabled=a!=null;ring.Progress=a==null?0:a.Elapsed/a.Duration;ring.Paused=a!=null&&!a.Running;ring.Resting=a!=null&&a.Kind!="focus";ring.InvalidateVisual();today.Text="今日已专注  "+Engine.Duration(app.Engine.DayTotal(DateTime.Today));
   if(task!=null&&task.IsGroup&&preview){phase.Text="任务组 · 合计专注";time.Text=Engine.Duration(NoteTasks.Total(app.Engine,task));time.FontSize=26;rounds.Text=GroupProgress(task);UI.IconLabel(toggle,"开始下一项","play");toggle.IsEnabled=NoteTasks.Next(app.Data,task)!=null;ring.Progress=GroupCompletion(task);ring.InvalidateVisual();}else time.FontSize=48;
  }
  public void EditTask(Todo task) {
   if(taskOverlay!=null)return;
   var panel=new StackPanel();var heading=UI.Columns(-1,30);var title=UI.Text(task==null?"想把时间花在哪里？":"给任务一点清晰的方向",20,"Ink");title.VerticalAlignment=VerticalAlignment.Center;heading.Children.Add(title);var dismiss=UI.Button("×",CloseEditor,false);dismiss.Padding=new Thickness(3);dismiss.Background=Brushes.Transparent;UI.At(heading,dismiss,0,1);heading.Margin=new Thickness(0,0,0,22);panel.Children.Add(heading);
   var name=UI.Input("任务名称",task==null?Engine.DefaultTaskTitle:task.Title);name.MaxLength=160;if(task!=null&&task.SourceBlockId!=null){name.IsReadOnly=true;name.ToolTip="在来源便签中修改标题，自动同步到这里";}panel.Children.Add(UI.Label("任务名称 · 可留空，默认自由专注"));panel.Children.Add(name);
   var grid=UI.Columns(-1,18,-1);grid.Margin=new Thickness(0,20,0,18);var minutes=UI.Input("每轮专注分钟",(task==null?app.Data.Settings.Focus:task.Minutes).ToString());var planned=UI.Input("预计番茄数",(task==null?4:task.Planned).ToString());UI.At(grid,UI.Stack(UI.Label("每轮专注 · 分钟"),minutes),0,0);UI.At(grid,UI.Stack(UI.Label("预计番茄数"),planned),0,2);panel.Children.Add(grid);
   var error=UI.Text("",12,"Accent");error.TextWrapping=TextWrapping.Wrap;error.MinHeight=34;panel.Children.Add(error);
   var save=UI.Button("保存任务",()=>{int m,p;if(!Int32.TryParse(minutes.Text,out m)||m<1||m>180||!Int32.TryParse(planned.Text,out p)||p<1||p>99){error.Text="专注时长为 1–180 分钟，预计番茄数为 1–99。";return;}var t=task??new Todo();t.Title=String.IsNullOrWhiteSpace(name.Text)?Engine.DefaultTaskTitle:name.Text.Trim();t.Minutes=m;t.Planned=p;if(task==null){app.Data.Tasks.Add(t);if(app.Data.Active==null)app.Data.Selected=t.Id;}app.Engine.Signal();CloseEditor();},true);save.IsDefault=true;panel.Children.Add(save);
   taskOverlay=new Grid {Background=new SolidColorBrush(Color.FromArgb(75,20,25,22))};KeyboardNavigation.SetTabNavigation(taskOverlay,KeyboardNavigationMode.Cycle);Grid.SetRowSpan(taskOverlay,2);Panel.SetZIndex(taskOverlay,10);var card=UI.Card(panel,new Thickness(28));card.Width=446;card.HorizontalAlignment=HorizontalAlignment.Center;card.VerticalAlignment=VerticalAlignment.Center;taskOverlay.Children.Add(card);((Grid)Content).Children.Add(taskOverlay);Dispatcher.BeginInvoke(new Action(()=>{if(taskOverlay!=null){name.Focus();if(task==null)name.SelectAll();}}));
  }
  internal void CloseEditor(){if(taskOverlay==null)return;((Grid)Content).Children.Remove(taskOverlay);taskOverlay=null;}
  void TaskHistory(Todo task) {
   var historyIds=new HashSet<string>((task.IsGroup?NoteTasks.Branch(app.Data,task):new List<Todo>{task}).Select(t=>t.Id));var w=UI.Dialog(this,"任务专注记录",540,520);var p=new StackPanel {Margin=new Thickness(24)};var name=UI.Text(task.Title,22,"Ink");name.TextWrapping=TextWrapping.Wrap;p.Children.Add(name);var summary=UI.Text("累计 "+Engine.Duration(task.IsGroup?NoteTasks.Total(app.Engine,task):app.Engine.Total(task.Id))+"  ·  完整番茄 "+(task.IsGroup?NoteTasks.Count(app.Engine,task):app.Engine.Count(task.Id))+" 个",13,"Muted");summary.Margin=new Thickness(0,12,0,22);p.Children.Add(summary);
   foreach(var s in app.Data.Sessions.Where(r=>historyIds.Contains(r.TaskId)).OrderByDescending(r=>r.StartUtc)){var line=UI.Text(s.StartUtc.ToLocalTime().ToString("MM月dd日 HH:mm")+"    "+Engine.Duration(s.Seconds)+"    "+(s.Complete?"完整番茄":"提前结束")+(s.TimestampRecovered?" · 日期为恢复估算":""),13,"Ink");line.Margin=new Thickness(0,0,0,14);p.Children.Add(line);}if(!app.Data.Sessions.Any(r=>historyIds.Contains(r.TaskId)))p.Children.Add(UI.Text("完成或结束专注后，记录会出现在这里。",13,"Muted"));w.Content=new ScrollViewer {Content=p};w.ShowDialog();
  }
  void BuildStats() {
   content.Children.Clear();var all=new StackPanel();all.Children.Add(Header("每一分钟，都有回响。","看看时间去了哪里，也看见自己的进步。",UI.Button("导出 CSV",()=>app.ExportCsv(this),false)));
   var metrics=UI.Columns(-1,12,-1,12,-1);int complete=app.Data.Sessions.Count(s=>s.Complete&&s.EndUtc.ToLocalTime().Date==DateTime.Today);UI.At(metrics,Metric("今日专注",Engine.Duration(app.Engine.DayTotal(DateTime.Today))),0,0);UI.At(metrics,Metric("今日番茄",complete+" 个"),0,2);UI.At(metrics,Metric("累计专注",Engine.Duration(app.Data.Tasks.Sum(t=>app.Engine.Total(t.Id)))),0,4);metrics.Margin=new Thickness(0,0,0,18);all.Children.Add(metrics);
   var chart=new StackPanel();var chartHeader=UI.Columns(-1,180);var ct=UI.Text("最近七天",15,"Ink");ct.FontWeight=FontWeights.SemiBold;chartHeader.Children.Add(ct);var cv=UI.Text("总计 "+Engine.Duration(Enumerable.Range(0,7).Sum(i=>app.Engine.DayTotal(DateTime.Today.AddDays(-i)))),11,"Muted");cv.HorizontalAlignment=HorizontalAlignment.Right;UI.At(chartHeader,cv,0,1);chart.Children.Add(chartHeader);
   var bars=UI.Columns(-1,-1,-1,-1,-1,-1,-1);bars.Margin=new Thickness(0,20,0,0);double max=Math.Max(60,Enumerable.Range(0,7).Max(i=>app.Engine.DayTotal(DateTime.Today.AddDays(-i))));
   for(int i=0;i<7;i++){var day=DateTime.Today.AddDays(i-6);double val=app.Engine.DayTotal(day);var col=new StackPanel();var amount=UI.Text(val<60?(val>0?"<1":"0"):((int)(val/60)).ToString(),10,"Muted");amount.HorizontalAlignment=HorizontalAlignment.Center;amount.Margin=new Thickness(0,0,0,8);col.Children.Add(amount);var plot=new Grid {Height=105};var bar=new Border {Width=24,Height=Math.Max(3,val/max*105),CornerRadius=new CornerRadius(5,5,2,2),VerticalAlignment=VerticalAlignment.Bottom};bar.SetResourceReference(Border.BackgroundProperty,i==6?"Accent":"Tint");bar.ToolTip=day.ToString("M月d日")+" · "+Engine.Duration(val);plot.Children.Add(bar);col.Children.Add(plot);var label=UI.Text(i==6?"今天":day.ToString("ddd"),10,"Muted");label.HorizontalAlignment=HorizontalAlignment.Center;label.Margin=new Thickness(0,10,0,0);col.Children.Add(label);UI.At(bars,col,0,i);}chart.Children.Add(bars);var foot=UI.Text("单位：分钟 · 不含暂停与休息",10,"Muted");foot.Margin=new Thickness(0,12,0,0);chart.Children.Add(foot);var chartCard=UI.Card(chart,new Thickness(22));chartCard.Margin=new Thickness(0,0,0,18);all.Children.Add(chartCard);
   var ranking=new StackPanel();var rankTitle=UI.Text("任务投入",16,"Ink");rankTitle.Margin=new Thickness(0,0,0,14);ranking.Children.Add(rankTitle);var ranked=app.Data.Tasks.Where(t=>app.Engine.Total(t.Id)>0).OrderByDescending(t=>app.Engine.Total(t.Id)).ToList();foreach(var t in ranked){var row=UI.Columns(-1,140);var name=UI.Text(t.Title,13,"Ink");name.TextTrimming=TextTrimming.CharacterEllipsis;row.Children.Add(name);var value=UI.Text(Engine.Duration(app.Engine.Total(t.Id)),12,"Muted");value.HorizontalAlignment=HorizontalAlignment.Right;UI.At(row,value,0,1);row.Margin=new Thickness(0,0,0,13);ranking.Children.Add(row);}if(ranked.Count==0)ranking.Children.Add(UI.Text("第一段专注，会从这里开始留下痕迹。",12,"Muted"));var rankCard=UI.Card(ranking,new Thickness(22));rankCard.Margin=new Thickness(0,0,0,18);all.Children.Add(rankCard);
   var records=new StackPanel();var recTitle=UI.Text("专注记录",16,"Ink");recTitle.Margin=new Thickness(0,0,0,15);records.Children.Add(recTitle);
   foreach(var session in app.Data.Sessions.OrderByDescending(s=>s.StartUtc).Take(100)){var s=session;var row=UI.Columns(-1,108,34);var name=UI.Text(s.Title,13,"Ink");name.TextTrimming=TextTrimming.CharacterEllipsis;var meta=UI.Text(s.StartUtc.ToLocalTime().ToString("MM-dd HH:mm")+" · "+(s.Complete?"完整番茄":"提前结束")+(s.TimestampRecovered?" · 日期为恢复估算":""),10,"Muted");meta.Margin=new Thickness(0,5,0,0);row.Children.Add(UI.Stack(name,meta));var dur=UI.Text(Engine.Duration(s.Seconds),11,"Muted");dur.VerticalAlignment=VerticalAlignment.Center;UI.At(row,dur,0,1);var del=UI.Button("×",()=>{if(MessageBox.Show(this,"删除这条专注记录？相关统计会同步更新。","删除记录",MessageBoxButton.OKCancel,MessageBoxImage.Question)==MessageBoxResult.OK){app.Data.Sessions.Remove(s);app.Engine.Signal();}},false);del.Padding=new Thickness(7);del.ToolTip="删除误操作记录";UI.At(row,del,0,2);row.Margin=new Thickness(0,0,0,16);records.Children.Add(row);}if(app.Data.Sessions.Count==0)records.Children.Add(UI.Text("还没有专注记录。",12,"Muted"));if(app.Data.Sessions.Count>100)records.Children.Add(UI.Text("显示最近 100 条，导出 CSV 可查看全部记录。",11,"Muted"));all.Children.Add(UI.Card(records,new Thickness(22)));content.Children.Add(new ScrollViewer {Content=all,Padding=new Thickness(0,0,9,0)});
  }
  Border Metric(string label,string value) {var l=UI.Label(label);var v=UI.Text(value,22,"Ink");v.FontWeight=FontWeights.SemiBold;return UI.Card(UI.Stack(l,v),new Thickness(20));}
  void BuildSettings() {
   var p=app.Data.Settings;var all=new StackPanel();all.Children.Add(Header("按你的节奏来。","简单的工具，也应该用着顺手。",null));
   var noteKeys=new StackPanel();noteKeys.Children.Add(SectionTitle("便签快捷键"));var shortcut=new ComboBox {Width=180,HorizontalAlignment=HorizontalAlignment.Left};foreach(var text in new[]{"Ctrl + Alt + N","Ctrl + Alt + M","关闭快捷键"})shortcut.Items.Add(text);shortcut.SelectedIndex=p.NoteShortcut=="off"?2:p.NoteShortcut=="M"?1:0;System.Windows.Automation.AutomationProperties.SetName(shortcut,"新建便签快捷键");var shortcutStatus=UI.Text(app.NoteShortcutAvailable?"随时新建便签 · 修改立即生效":"快捷键被占用，请选择另一个组合。",11,"Muted");shortcutStatus.Margin=new Thickness(0,10,0,0);shortcut.SelectionChanged+=(s,e)=>{p.NoteShortcut=new[]{"N","M","off"}[shortcut.SelectedIndex];app.RegisterNoteShortcut();bool saved=app.Save();shortcutStatus.Text=!saved?"尚未保存，请重试。":app.NoteShortcutAvailable?"已更新 · 修改立即生效":"快捷键被其他软件占用，请换一个组合。";};noteKeys.Children.Add(shortcut);noteKeys.Children.Add(shortcutStatus);all.Children.Add(SettingsCard(noteKeys));
   var startupPanel=new StackPanel();startupPanel.Children.Add(SectionTitle("启动"));
   var startupCheck=new CheckBox {Content="开机自启",Margin=new Thickness(0,0,0,8)};AutomationProperties.SetName(startupCheck,"开机自启");
   var startupHelp=UI.Text("登录 Windows 后在后台运行，不弹出主界面。开关更改立即生效。",11,"Muted");startupHelp.TextWrapping=TextWrapping.Wrap;startupHelp.LineHeight=20;
   var startupStatus=UI.Text("",11,"Muted");startupStatus.Margin=new Thickness(0,8,0,0);startupStatus.TextWrapping=TextWrapping.Wrap;
   Action readStartup=()=>{startupStatus.SetResourceReference(TextBlock.ForegroundProperty,"Muted");try{startupCheck.IsChecked=app.Startup.IsRegistered;startupStatus.Text=startupCheck.IsChecked==true?(app.Startup.UsesCurrentPath?"已开启 · 仅对当前 Windows 用户生效":"已登记旧位置 · 关闭后重新开启可更新路径"):"已关闭";}catch(Exception ex){startupCheck.IsEnabled=false;startupStatus.Text="暂时无法读取启动设置："+ex.Message;}};
   readStartup();startupCheck.Click+=(s,e)=>{try{app.Startup.SetEnabled(startupCheck.IsChecked==true);readStartup();}catch(Exception ex){readStartup();startupStatus.Text="未能更改开机自启："+ex.Message;startupStatus.SetResourceReference(TextBlock.ForegroundProperty,"Accent");}};
   startupPanel.Children.Add(startupCheck);startupPanel.Children.Add(startupHelp);startupPanel.Children.Add(startupStatus);all.Children.Add(SettingsCard(startupPanel));
   var timing=new StackPanel();timing.Children.Add(SectionTitle("专注与休息"));var grid=UI.Columns(-1,14,-1,14,-1,14,-1);var focus=UI.Input("默认专注分钟",p.Focus.ToString());var shortB=UI.Input("短休息分钟",p.ShortBreak.ToString());var longB=UI.Input("长休息分钟",p.LongBreak.ToString());var roundsBox=UI.Input("长休息间隔",p.Rounds.ToString());UI.At(grid,UI.Stack(UI.Label("默认专注 / 分钟"),focus),0,0);UI.At(grid,UI.Stack(UI.Label("短休息 / 分钟"),shortB),0,2);UI.At(grid,UI.Stack(UI.Label("长休息 / 分钟"),longB),0,4);UI.At(grid,UI.Stack(UI.Label("每几轮长休息"),roundsBox),0,6);timing.Children.Add(grid);
   var lockCheck=new CheckBox {Content="锁屏时自动暂停（睡眠始终暂停）",IsChecked=p.PauseOnLock};var sound=new CheckBox {Content="阶段结束时播放轻提示音",IsChecked=p.Sound};var notification=new CheckBox {Content="阶段结束时显示桌面通知",IsChecked=p.Notifications};timing.Children.Add(lockCheck);timing.Children.Add(sound);timing.Children.Add(notification);all.Children.Add(SettingsCard(timing));
   var visual=new StackPanel();visual.Children.Add(SectionTitle("外观与计时条"));var themeRow=UI.Row();var system=new RadioButton {Content="跟随系统",GroupName="theme",IsChecked=p.Theme=="system",Margin=new Thickness(0,0,22,0)};var light=new RadioButton {Content="浅色",GroupName="theme",IsChecked=p.Theme=="light",Margin=new Thickness(0,0,22,0)};var dark=new RadioButton {Content="深色",GroupName="theme",IsChecked=p.Theme=="dark"};foreach(var r in new[]{system,light,dark}){r.SetResourceReference(Control.ForegroundProperty,"Ink");themeRow.Children.Add(r);}themeRow.Margin=new Thickness(0,0,0,12);visual.Children.Add(themeRow);
   var show=new CheckBox {Content="显示任务栏计时条",IsChecked=p.ShowBar};var locked=new CheckBox {Content="锁定计时条位置（取消后可横向拖动）",IsChecked=p.Locked};visual.Children.Add(show);visual.Children.Add(locked);
   var offset=UI.Input("计时条左侧距离",p.Offset.ToString());offset.Width=100;offset.HorizontalAlignment=HorizontalAlignment.Left;var position=UI.Row(UI.Text("距任务栏左侧",12,"Muted"),offset,UI.Text("  像素 · -1 为自动",11,"Muted"));foreach(FrameworkElement item in position.Children)item.VerticalAlignment=VerticalAlignment.Center;offset.Margin=new Thickness(16,0,0,0);position.Margin=new Thickness(0,12,0,8);visual.Children.Add(position);var mode=UI.Text("当前显示："+(app.Bar==null?"自动适配":app.Bar.Mode)+"  ·  全屏时自动隐藏",11,"Muted");mode.Margin=new Thickness(0,8,0,0);visual.Children.Add(mode);all.Children.Add(SettingsCard(visual));
   var status=UI.Text("",12,"Accent");status.TextWrapping=TextWrapping.Wrap;status.Margin=new Thickness(0,0,0,10);all.Children.Add(status);
   var save=UI.Button("保存设置",()=>{int f,s,l,r,o;if(!Int32.TryParse(focus.Text,out f)||f<1||f>180||!Int32.TryParse(shortB.Text,out s)||s<1||s>60||!Int32.TryParse(longB.Text,out l)||l<1||l>120||!Int32.TryParse(roundsBox.Text,out r)||r<1||r>12||!Int32.TryParse(offset.Text,out o)||o< -1||o>10000){status.Text="请输入有效数值：专注 1–180，短休息 1–60，长休息 1–120，间隔 1–12，位置 -1–10000。";return;}p.Focus=f;p.ShortBreak=s;p.LongBreak=l;p.Rounds=r;p.PauseOnLock=lockCheck.IsChecked==true;p.Sound=sound.IsChecked==true;p.Notifications=notification.IsChecked==true;p.ShowBar=show.IsChecked==true;p.Locked=locked.IsChecked==true;p.Offset=o;p.Theme=dark.IsChecked==true?"dark":light.IsChecked==true?"light":"system";app.ApplyTheme();if(!app.Save()){status.Text="设置尚未保存成功，请稍后重试。";return;}if(app.Bar!=null)app.Bar.RefreshPlacement();status.Text="设置已保存。新的默认时长用于新任务，当前计时不受影响。";},true);save.HorizontalAlignment=HorizontalAlignment.Left;save.Margin=new Thickness(0,0,0,24);all.Children.Add(save);
   var data=new StackPanel();data.Children.Add(SectionTitle("数据与你"));var buttons=UI.Row(UI.Button("备份数据",()=>app.Backup(this),false),UI.Button("恢复备份",()=>app.Restore(this),false),UI.Button("打开数据目录",()=>System.Diagnostics.Process.Start(app.Store.DirectoryPath),false));foreach(FrameworkElement b in buttons.Children)b.Margin=new Thickness(0,0,10,0);data.Children.Add(buttons);var path=UI.Text(app.Store.DirectoryPath,11,"Muted");path.TextWrapping=TextWrapping.Wrap;path.Margin=new Thickness(0,14,0,0);data.Children.Add(path);var help=UI.Text("自动保存并保留上一份备份。关闭窗口后继续计时，右键计时条或托盘图标可退出。\n快捷键：Ctrl + Alt + P 暂停 / 继续，Ctrl + Alt + O 打开主界面。\n小番茄 1.6.0 · 本地运行，无账号、无联网服务。",11,"Muted");help.TextWrapping=TextWrapping.Wrap;help.LineHeight=22;help.Margin=new Thickness(0,12,0,0);data.Children.Add(help);all.Children.Add(SettingsCard(data));content.Children.Add(new ScrollViewer {Content=all,Padding=new Thickness(0,0,9,0)});
  }
  TextBlock SectionTitle(string text) {var t=UI.Text(text,16,"Ink");t.FontWeight=FontWeights.SemiBold;t.Margin=new Thickness(0,0,0,18);return t;}
  Border SettingsCard(UIElement child) {var c=UI.Card(child,new Thickness(22));c.Margin=new Thickness(0,0,0,16);return c;}
 }
 public class MiniWindow : Window {
  Program app;TextBlock title,time,phase,caption;Button toggle,end;StackPanel picker;bool choosing;Border progress;
  public MiniWindow(Program owner) {
   app=owner;Style=(Style)Application.Current.FindResource(typeof(Window));Title="小番茄 · 当前任务";Width=336;SizeToContent=SizeToContent.Height;WindowStyle=WindowStyle.None;ResizeMode=ResizeMode.NoResize;ShowInTaskbar=false;Topmost=true;Background=Brushes.Transparent;AllowsTransparency=true;UseLayoutRounding=true;
   var p=new StackPanel();var header=UI.Columns(26,-1,28);header.Height=28;header.Children.Add(UI.Tomato(22));phase=UI.Text("正在专注",11,"Muted");phase.VerticalAlignment=VerticalAlignment.Center;phase.Margin=new Thickness(8,0,0,0);UI.At(header,phase,0,1);var close=UI.Button("",()=>Hide(),false);UI.IconLabel(close,"","close");close.Padding=new Thickness(6);close.Background=Brushes.Transparent;close.ToolTip="收起面板";UI.At(header,close,0,2);p.Children.Add(header);
   title=UI.Text("自由专注",18,"Ink");title.FontWeight=FontWeights.SemiBold;title.TextTrimming=TextTrimming.CharacterEllipsis;title.Margin=new Thickness(0,18,0,10);p.Children.Add(title);
   var clockRow=UI.Columns(-1,76);time=UI.Text("25:00",48,"Ink");time.FontFamily=new FontFamily("Segoe UI");time.FontWeight=FontWeights.Normal;Typography.SetNumeralAlignment(time,FontNumeralAlignment.Tabular);clockRow.Children.Add(time);caption=UI.Text("剩余时间",11,"Muted");caption.VerticalAlignment=VerticalAlignment.Bottom;caption.HorizontalAlignment=HorizontalAlignment.Right;caption.Margin=new Thickness(0,0,0,12);UI.At(clockRow,caption,0,1);p.Children.Add(clockRow);
   progress=new Border {Height=4,CornerRadius=new CornerRadius(2),HorizontalAlignment=HorizontalAlignment.Left};progress.SetResourceReference(Border.BackgroundProperty,"Accent");var track=new Border {Height=4,CornerRadius=new CornerRadius(2),Margin=new Thickness(0,12,0,22),Child=progress};track.SetResourceReference(Border.BackgroundProperty,"Soft");track.SizeChanged+=(s,e)=>Refresh();p.Children.Add(track);
   var buttons=UI.Columns(-1,10,86);toggle=UI.Button("暂停",()=>{app.ToggleTimer();Refresh();},true);toggle.Height=42;end=UI.Button("结束",()=>{app.EndTimer();Refresh();},false);end.Padding=new Thickness(12,8,12,8);buttons.Children.Add(toggle);UI.At(buttons,end,0,2);p.Children.Add(buttons);
   var links=UI.Columns(-1,8,-1);links.Margin=new Thickness(0,16,0,0);var choose=UI.Button("切换任务",()=>{choosing=!choosing;FillPicker();},false);UI.IconLabel(choose,"切换任务","down");choose.HorizontalContentAlignment=HorizontalAlignment.Left;var open=UI.Button("主界面",()=>app.ShowMain(),false);UI.IconLabel(open,"主界面","open");open.HorizontalContentAlignment=HorizontalAlignment.Right;foreach(var b in new[]{choose,open}){b.FontSize=11;b.Padding=new Thickness(0,7,0,7);b.Background=Brushes.Transparent;b.SetResourceReference(Control.ForegroundProperty,"Muted");}links.Children.Add(choose);UI.At(links,open,0,2);p.Children.Add(links);picker=new StackPanel();p.Children.Add(picker);
   var card=UI.Card(p,new Thickness(24,18,24,16));card.CornerRadius=new CornerRadius(18);card.Margin=new Thickness(10);card.Effect=new System.Windows.Media.Effects.DropShadowEffect {BlurRadius=15,ShadowDepth=3,Opacity=.12,Color=Colors.Black};Content=card;Deactivated+=(s,e)=>Hide();PreviewKeyDown+=(s,e)=>{if(e.Key==Key.Escape)Hide();};
  }
  void FillPicker() {picker.Children.Clear();if(!choosing)return;var tasks=app.Data.Tasks.Where(t=>!t.Done&&!t.Archived).ToList();var list=new StackPanel();foreach(var t0 in tasks){var t=t0;var b=UI.Button(t.Title,()=>{app.StartTask(t);choosing=false;FillPicker();Refresh();},false);b.HorizontalContentAlignment=HorizontalAlignment.Left;b.Margin=new Thickness(0,5,0,0);b.ToolTip=t.Title;var text=UI.Text(t.Title,12,"Ink");text.TextTrimming=TextTrimming.CharacterEllipsis;b.Content=text;list.Children.Add(b);}if(tasks.Count==0)list.Children.Add(UI.Button("＋ 新建任务",()=>{app.ShowMain();app.Main.EditTask(null);},false));picker.Children.Add(new ScrollViewer {Content=list,MaxHeight=180,Margin=new Thickness(0,8,0,0)});Dispatcher.BeginInvoke(new Action(Position));}
  public void Refresh() {var a=app.Data.Active;bool paused=a!=null&&!a.Running;title.Text=app.Engine.Current==null?"自由专注":app.Engine.Current.Title;title.ToolTip=title.Text;phase.Text=a==null?"准备好，开始一段专注":paused?"已暂停 · 随时继续":a.Kind=="focus"?"正在专注":"休息时间";time.Text=app.Engine.DisplayTime;caption.Text=paused?"计时已暂停":"剩余时间";UI.IconLabel(toggle,a==null?"开始专注":a.Running?"暂停":a.Kind=="focus"?"继续专注":"继续休息",a!=null&&a.Running?"pause":"play");end.Content=a!=null&&a.Kind!="focus"?"跳过":"结束";end.IsEnabled=a!=null;var track=progress.Parent as Border;progress.Width=Math.Max(0,(track==null?266:track.ActualWidth)*Math.Max(0,Math.Min(1,a==null?0:a.Elapsed/a.Duration)));progress.SetResourceReference(Border.BackgroundProperty,paused?"Muted":a!=null&&a.Kind!="focus"?"Green":"Accent");}
  public void Open() {choosing=app.Engine.Current==null;FillPicker();Refresh();Show();UpdateLayout();Position();Activate();Native.SetForegroundWindow(new WindowInteropHelper(this).Handle);}
  void Position() {if(app.Bar==null)return;Native.RECT r;Native.GetWindowRect(app.Bar.Handle,out r);var source=PresentationSource.FromVisual(this);var transform=source==null?Matrix.Identity:source.CompositionTarget.TransformFromDevice;var pt=transform.Transform(new Point(r.Left,r.Top));var screen=System.Windows.Forms.Screen.FromHandle(app.Bar.Handle);var area=screen.WorkingArea;var start=transform.Transform(new Point(area.Left,area.Top));var end=transform.Transform(new Point(area.Right,area.Bottom));Left=Math.Max(start.X+6,Math.Min(pt.X,end.X-Width-6));Top=Math.Max(start.Y+6,Math.Min(pt.Y-ActualHeight-8,end.Y-ActualHeight-6));}
 }
}
